(() => {
"use strict";
const KEY="upaon-acu-v5";
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
const fmt=n=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(Math.max(0,n));
const money=n=>"¤ "+new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(Math.max(0,n));
const $=id=>document.getElementById(id);

const START_CONTEXTS={
 upaon:["Upaon-Açu","Núcleo atlântico, posição marítima e forte potencial de centralização."],brasil:["Brasil","Grande espaço territorial, recursos naturais e múltiplas fronteiras."],amazonia:["Amazônia","Rede fluvial extensa, baixa densidade e enorme fronteira de recursos."],nordeste:["Nordeste Atlântico","Litoral comercial, agricultura e portos estratégicos."],caribe:["Caribe","Arquipélago estratégico entre as Américas e as rotas atlânticas."],iberia:["Península Ibérica","Navegação avançada, Estados centralizados e rivalidades continentais."],africa:["África Ocidental","Rios, comércio e cidades costeiras conectam o interior ao Atlântico."],india:["Índia","Grande população, comércio oceânico e tradição científica."],china:["China","Alta escala populacional, administração e capacidade produtiva."]};

const nationTemplate={
 portugal:{name:"Portugal",flag:"🇵🇹",region:"Europa",military:30,economy:50,science:42,stability:68,attitude:18,trade:18,tension:15,territory:9,alliance:null},
 espanha:{name:"Espanha",flag:"🇪🇸",region:"Europa",military:34,economy:52,science:40,stability:64,attitude:10,trade:10,tension:20,territory:10,alliance:null},
 franca:{name:"França",flag:"🇫🇷",region:"Europa",military:38,economy:56,science:58,stability:65,attitude:24,trade:12,tension:8,territory:14,alliance:null},
 holanda:{name:"Países Baixos",flag:"🇳🇱",region:"Europa",military:26,economy:62,science:50,stability:70,attitude:22,trade:20,tension:10,territory:7,alliance:null},
 inglaterra:{name:"Inglaterra",flag:"🇬🇧",region:"Europa",military:43,economy:65,science:55,stability:67,attitude:18,trade:15,tension:12,territory:12,alliance:null},
 china:{name:"China",flag:"🇨🇳",region:"Ásia",military:46,economy:72,science:48,stability:72,attitude:10,trade:5,tension:3,territory:45,alliance:null},
 india:{name:"Índia",flag:"🇮🇳",region:"Ásia",military:32,economy:60,science:52,stability:62,attitude:14,trade:8,tension:4,territory:30,alliance:null},
 magrebe:{name:"Magrebe",flag:"🌍",region:"África",military:25,economy:40,science:35,stability:60,attitude:26,trade:11,tension:5,territory:12,alliance:null},
 caribe:{name:"Confederação Caribenha",flag:"🏝️",region:"Caribe",military:20,economy:38,science:30,stability:58,attitude:32,trade:14,tension:7,territory:5,alliance:null},
 brasil:{name:"Estados do Brasil",flag:"🌎",region:"Américas",military:28,economy:45,science:30,stability:55,attitude:15,trade:9,tension:10,territory:35,alliance:null}
};

const PEOPLE_PROFILES={
 upaonense:{name:"Povo Upaonense",culture:"Civilização insular atlântica",pop:1.0,food:1.05,wood:1.05,military:0,science:0,industry:0,education:1,urban:0},
 tupi:{name:"Povo Tupi",culture:"Confederação de povos de tradição tupi",pop:1.35,food:1.12,wood:1.15,military:1,science:0,industry:-1,education:0,urban:-1},
 africano:{name:"Reino Atlântico Africano",culture:"Monarquia comercial atlântica",pop:2.2,food:1.25,wood:1.1,military:5,science:2,industry:2,education:2,urban:3},
 iberico:{name:"Reino Ibérico",culture:"Estado marítimo europeu",pop:3.0,food:1.0,wood:.9,military:10,science:6,industry:5,education:5,urban:8},
 indico:{name:"Reino do Índico",culture:"Potência comercial do oceano Índico",pop:6.0,food:1.2,wood:.95,military:6,science:8,industry:4,education:8,urban:10},
 sinico:{name:"Estado Sínico",culture:"Estado burocrático e produtivo do leste asiático",pop:8.0,food:1.35,wood:.9,military:9,science:7,industry:8,education:10,urban:12},
 custom:{name:"Povo personalizado",culture:"Civilização emergente",pop:1.0,food:1.0,wood:1.0,military:0,science:0,industry:0,education:0,urban:0}
};

const initial={year:1460,round:1,actionsLeft:5,selectedActions:[],population:18000,urban:7,territory:1,stability:72,economy:38,science:8,industry:12,technology:5,military:7,diplomacyPower:18,education:9,health:8,energy:3,infrastructure:8,readiness:18,treasury:120,food:100,iron:22,wood:70,machines:4,energyStock:15,trade:20,
 lastReport:null,lastGlobal:null,censuses:[],history:[{year:1460,text:"Fundação e centralização de Upaon-Açu."}],warStatus:{},alliances:[],sanctions:[],influence:{},warsWon:0,warsLost:0,
 tech:{mecanica:0,quimica:0,medicina:0,microbiologia:0,eletricidade:0,automacao:0,controle:0,naval:0,submersiveis:0,aeronautica:0,aerodinamica:0,navegacao:0,computacao:0,programacao:0,dados:0,semfio:0,sistemas:0,industria:0},
 selectedRegion:"upaon",mapMode:"world",
 workforce:{agro:48,pesca:12,construcao:8,minera:4,manufatura:15,industria:3,navegacao:3,servicos:4,ciencia:1,outros:2},
 cities:{saoLuis:{name:"São Luís",pop:12000,industry:8,infra:14,science:8,port:20,education:10,health:8}},
 nations:structuredClone(nationTemplate),
 relations:Object.fromEntries(Object.entries(nationTemplate).map(([k,n])=>[k,{name:n.name,trust:20,trade:n.trade,tension:n.tension,science:3,alliance:null}]))
};
let S=structuredClone(initial);

const actions=[
{id:"admin",icon:"🏛️",cat:"Estado",name:"Reforma administrativa",desc:"Fortalece governança, arrecadação e infraestrutura pública.",cost:"¤ −8 • 1 AP",apply(){S.stability+=5;S.infrastructure+=2;S.economy+=1;S.treasury-=8}},
{id:"edu",icon:"🎓",cat:"Educação",name:"Expandir educação",desc:"Forma professores, técnicos e futuros pesquisadores.",cost:"¤ −10 • 1 AP",apply(){S.education+=6;S.science+=2;S.treasury-=10}},
{id:"science",icon:"🔬",cat:"Ciência",name:"Instituto científico",desc:"Financia química, física, medicina e engenharia.",cost:"¤ −12 • 1 AP",apply(){S.science+=6;S.technology+=2;S.treasury-=12;S.tech.mecanica+=.3}},
{id:"industry",icon:"🏭",cat:"Indústria",name:"Complexo industrial",desc:"Amplia máquinas, manufatura e produção nacional.",cost:"Fe −4 • ¤ −15 • 2 AP",ap:2,apply(){S.industry+=7;S.economy+=2;S.infrastructure+=2;S.iron-=4;S.machines+=1;S.treasury-=15;S.workforce.industria+=2;S.workforce.agro-=2}},
{id:"energy",icon:"⚡",cat:"Energia",name:"Programa energético",desc:"Aumenta geração e capacidade industrial.",cost:"Madeira −6 • ¤ −10 • 1 AP",apply(){S.energy+=7;S.industry+=2;S.infrastructure+=3;S.wood-=6;S.energyStock+=12;S.treasury-=10}},
{id:"health",icon:"🏥",cat:"Saúde",name:"Campanha sanitária",desc:"Saneamento e medicina elevam sobrevivência e estabilidade.",cost:"¤ −10 • 1 AP",apply(){S.health+=7;S.stability+=2;S.population*=1.004;S.treasury-=10}},
{id:"transport",icon:"🚂",cat:"Transporte",name:"Rede de transporte",desc:"Estradas, portos e vias internas conectam mercados.",cost:"Madeira −8 • ¤ −12 • 1 AP",apply(){S.infrastructure+=8;S.economy+=4;S.urban+=1;S.wood-=8;S.treasury-=12}},
{id:"naval",icon:"⚓",cat:"Naval",name:"Programa naval",desc:"Estaleiros ampliam comércio, projeção e defesa marítima.",cost:"Madeira −10 • Fe −3 • 1 AP",apply(){S.military+=2;S.infrastructure+=3;S.diplomacyPower+=2;S.tech.naval+=1;S.economy+=2;S.wood-=10;S.iron-=3}},
{id:"aero",icon:"✈️",cat:"Aeronáutica",name:"Pesquisa aeronáutica",desc:"Desenvolve aerostatos, aerodinâmica e voo experimental.",cost:"¤ −14 • 1 AP",apply(){S.science+=3;S.technology+=4;S.tech.aeronautica+=1;S.tech.aerodinamica+=.5;S.industry+=2;S.treasury-=14}},
{id:"compute",icon:"💻",cat:"Computação",name:"Laboratório de informação",desc:"Cálculo, codificação, memória e processamento.",cost:"¤ −15 • 2 AP",ap:2,apply(){S.science+=3;S.technology+=5;S.tech.computacao+=1;S.tech.dados+=1;S.tech.programacao+=.5;S.treasury-=15}},
{id:"mil",icon:"🪖",cat:"Militar",name:"Fortalecimento militar",desc:"Treinamento, logística e engenharia aumentam prontidão.",cost:"¤ −12 • Alimento −4 • 1 AP",apply(){S.military+=5;S.readiness+=8;S.treasury-=12;S.food-=4}},
{id:"dip",icon:"🌎",cat:"Diplomacia",name:"Missão diplomática",desc:"Amplia confiança, comércio e cooperação científica.",cost:"¤ −5 • 1 AP",apply(){S.diplomacyPower+=7;S.economy+=3;S.treasury-=5;Object.values(S.relations).forEach(x=>x.trust=clamp(x.trust+2))}},
{id:"trade",icon:"🤝",cat:"Economia",name:"Acordo comercial",desc:"Gera receita e aumenta rotas comerciais.",cost:"¤ −3 • 1 AP",apply(){S.economy+=4;S.trade+=7;S.diplomacyPower+=2;S.treasury-=3}},
{id:"census",icon:"📋",cat:"Estado",name:"Censo nacional",desc:"Registra população e melhora a capacidade administrativa.",cost:"Estabilidade −1 • 1 AP",apply(){doCensus(true);S.stability-=1}},
{id:"resources",icon:"⛏️",cat:"Recursos",name:"Expedição mineral",desc:"Procura ferro, madeira e matérias-primas.",cost:"¤ −7 • 1 AP",apply(){S.iron+=7+Math.random()*4;S.wood+=8;S.treasury-=7;S.industry+=1}},
{id:"urban",icon:"🏙️",cat:"Cidades",name:"Plano urbano",desc:"Habitação e infraestrutura aceleram urbanização.",cost:"¤ −9 • 1 AP",apply(){S.infrastructure+=5;S.urban+=3;S.treasury-=9;S.cities.saoLuis.infra+=5}},
{id:"influence",icon:"🕸️",cat:"Estratégia",name:"Rede de influência",desc:"Financia presença comercial e política em uma potência.",cost:"¤ −6 • 1 AP",apply(){const id=targetId();const d=S.relations[id],n=S.nations[id];d.trust=clamp(d.trust+7);n.attitude=clamp(n.attitude+4,-100,100);S.influence[id]=(S.influence[id]||0)+10;S.treasury-=6;S.diplomacyPower+=4}},
{id:"fort",icon:"🧱",cat:"Defesa",name:"Fortificações estratégicas",desc:"Defende portos e aumenta a capacidade de resistir a invasões.",cost:"Fe −3 • ¤ −10 • 1 AP",apply(){S.military+=3;S.readiness+=5;S.infrastructure+=2;S.iron-=3;S.treasury-=10}},
{id:"intelligence",icon:"🛰️",cat:"Inteligência",name:"Serviço de inteligência",desc:"Melhora contraespionagem e leitura do equilíbrio internacional.",cost:"¤ −8 • 1 AP",apply(){S.science+=2;S.technology+=2;S.readiness+=2;S.treasury-=8}}
];

const tech=[
["mecanica","Mecânica","Máquinas e mecanismos",1460],["quimica","Química","Materiais e processos",1480],["medicina","Medicina","Saúde científica",1475],["microbiologia","Microbiologia","Doenças e microrganismos",1510],["eletricidade","Eletricidade","Geração e motores",1540],["automacao","Automação","Máquinas automáticas",1580],["controle","Controle","Sistemas de controle",1600],["naval","Engenharia naval","Estaleiros e navegação",1460],["submersiveis","Submersíveis","Exploração submarina",1530],["aeronautica","Aeronáutica","Aeronaves",1580],["aerodinamica","Aerodinâmica","Voo eficiente",1600],["navegacao","Navegação aérea","Instrumentação",1610],["computacao","Computação","Máquinas de informação",1590],["programacao","Programação","Lógica computacional",1620],["dados","Processamento de dados","Informação em escala",1630],["semfio","Comunicação sem fio","Comunicação estratégica",1645],["sistemas","Engenharia de sistemas","Integração tecnológica",1610],["industria","Indústria","Produção mecanizada",1500]
];
const milestones=[[1500,"Primeira fase industrial","Metalurgia, escrita e administração ganham escala."],[1530,"Era das máquinas térmicas","Engenharia e energia começam a transformar a economia."],[1560,"Sociedade mecanizada","Indústria, eletricidade e transportes entram em expansão."],[1590,"Era da automação","Precisão, controle e informação tornam-se estratégicos."],[1620,"Era da Aeronáutica","Sistemas de voo, cálculo e engenharia integrada avançam."],[1650,"Era da Informação Sem Fio","Comunicação e processamento de dados reorganizam o Estado."],[1665,"Era dos Sistemas","Engenharia de sistemas conecta indústria, ciência e poder nacional."]];

function era(){if(S.year<1500)return"Era da Fundação";if(S.year<1530)return"Era Industrial Inicial";if(S.year<1560)return"Era das Máquinas Térmicas";if(S.year<1590)return"Era Elétrica";if(S.year<1620)return"Era da Automação";if(S.year<1650)return"Era da Aeronáutica";if(S.year<1665)return"Era da Informação";return"Era dos Sistemas"}
function targetId(){return $("attackTarget")?.value || Object.keys(S.nations)[0]}
function setupPreview(){const l=START_CONTEXTS[$("startLocation").value],y=$("startYear").value,pid=$("startPeople").value,p=PEOPLE_PROFILES[pid]||PEOPLE_PROFILES.custom;$("startPreview").innerHTML=`<b>${l[0]}</b> • ${p.name} • ${y}<br>${l[1]}<br><small>${p.culture}. A campanha começa com <b>5 AP</b> e contexto ajustado à região, povo e época.</small>`}
["startLocation","startPeople","startYear"].forEach(id=>$(id).addEventListener("change",setupPreview));setupPreview();
function startCampaign(){
 const y=+$('startYear').value,loc=$('startLocation').value,peopleId=$('startPeople').value,people=PEOPLE_PROFILES[peopleId]||PEOPLE_PROFILES.custom;
 S=structuredClone(initial);S.year=y;S.round=1;S.startLocation=loc;S.startPeople=people.name;S.startPeopleId=peopleId;S.actionsLeft=5;S.selectedActions=[];S.selectedRegion="upaon";S.mapMode="world";S.diplomacyPower=18;
 S.history=[{year:y,text:`Campanha iniciada em ${START_CONTEXTS[loc][0]} como ${people.name}.`}];
 const scale=Math.max(0,(y-1460)/10);
 S.population*=Math.pow(1.006,scale)*people.pop;S.food*=people.food;S.wood*=people.wood;
 S.economy=clamp(S.economy+scale*.5+people.industry);S.science=clamp(S.science+scale*.7+people.science);S.industry=clamp(S.industry+scale*.65+people.industry);S.technology=clamp(S.technology+scale*.8+people.science*.4);S.infrastructure=clamp(S.infrastructure+scale*.55);S.education=clamp(S.education+scale*.5+people.education);S.health=clamp(S.health+scale*.45);S.military=clamp(S.military+scale*.45+people.military);S.urban=clamp(S.urban+scale*.3+people.urban,0,96);
 if(loc==="china")S.population*=1.25;if(loc==="india")S.population*=1.1;if(["brasil","amazonia","nordeste"].includes(loc)){S.population*=1.35;S.wood*=1.25;S.food*=1.2}if(loc==="iberia"){S.military+=5;S.economy+=8}
 clampAll();$('startScreen').classList.add('hidden');render();toast(`Campanha iniciada em ${y} como ${people.name}.`)
}
$("startGame").onclick=startCampaign;

function render(){
 $("year").textContent=S.year;$("round").textContent=S.round;$("eraName").textContent=era();$("actionCount").textContent=`${S.actionsLeft} AP restantes`;
 $("headline").textContent=S.year<1500?"O nascimento de uma civilização":S.year<1600?"Uma potência em transformação":"Uma civilização tecnológica em ascensão";
 $("statusText").textContent=`${fmt(S.population)} habitantes • ${Math.round(S.urban)}% urbanos • ${S.warsWon} guerras vencidas • ${S.alliances.length} alianças`;
 $("actionDots").innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<S.actionsLeft?"on":""}"></i>`).join("");
 $("metrics").innerHTML=[['👥','População',fmt(S.population)],['🏙️','Urbanização',Math.round(S.urban)+'%'],['💰','Tesouro',money(S.treasury)],['🌾','Alimento',fmt(S.food)],['⚙️','Indústria',Math.round(S.industry)],['🔬','Ciência',Math.round(S.science)],['🧠','Tecnologia',Math.round(S.technology)],['⚔️','Militar',Math.round(S.military)],['🕊️','Diplomacia',Math.round(S.diplomacyPower)],['🛡️','Prontidão',Math.round(S.readiness)]].map(x=>`<div class="metric"><span>${x[0]}</span><small>${x[1]}</small><b>${x[2]}</b></div>`).join('');
 renderActions();renderTech();renderEconomy();renderMap();renderSociety();renderMilitary();renderDiplomacy();renderTimeline();populateTargets();
 $("latestEvent").textContent=S.history.at(-1)?.text||"Nenhum evento registrado.";
}
function renderActions(){
 $("actionGrid").innerHTML=actions.map(a=>`<button class="action" data-action="${a.id}" ${S.actionsLeft<(a.ap||1)?"disabled":""}><span class="icon">${a.icon}</span><span class="cat">${a.cat} • ${a.ap||1} AP</span><h3>${a.name}</h3><p>${a.desc}</p><span class="cost">${a.cost}</span></button>`).join('');
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>executeAction(b.dataset.action));
}
function executeAction(id){const a=actions.find(x=>x.id===id);if(!a)return;const ap=a.ap||1;const requirements={industry:[['iron',4,'Ferro insuficiente.'],['treasury',15,'Tesouro insuficiente.']],energy:[['wood',6,'Madeira insuficiente.'],['treasury',10,'Tesouro insuficiente.']],transport:[['wood',8,'Madeira insuficiente.'],['treasury',12,'Tesouro insuficiente.']],naval:[['wood',10,'Madeira insuficiente.'],['iron',3,'Ferro insuficiente.']],compute:[['treasury',15,'Tesouro insuficiente.']],mil:[['food',4,'Alimento insuficiente.'],['treasury',12,'Tesouro insuficiente.']],fort:[['iron',3,'Ferro insuficiente.'],['treasury',10,'Tesouro insuficiente.']],admin:[['treasury',8,'Tesouro insuficiente.']],edu:[['treasury',10,'Tesouro insuficiente.']],science:[['treasury',12,'Tesouro insuficiente.']],health:[['treasury',10,'Tesouro insuficiente.']],trade:[['treasury',3,'Tesouro insuficiente.']],resources:[['treasury',7,'Tesouro insuficiente.']],urban:[['treasury',9,'Tesouro insuficiente.']],influence:[['treasury',6,'Tesouro insuficiente.']],intelligence:[['treasury',8,'Tesouro insuficiente.']]};if(S.actionsLeft<ap)return toast('Pontos de ação insuficientes.');for(const [key,value,msg] of (requirements[id]||[])){if((S[key]||0)<value)return toast(msg)}S.actionsLeft-=ap;a.apply();S.selectedActions.push(a.name);S.history.push({year:S.year,text:`${a.name}.`});clampAll();render();toast(`${a.name} executada.`)}
function renderTech(){$("techTree").innerHTML=tech.map(([id,n,d,req])=>{const level=Number(S.tech[id]||0),unlock=S.year>=req,done=level>=1;return `<div class="tech ${unlock?"":"locked"} ${done?"done":""}"><h3>${n}</h3><p>${d}</p><div class="bar"><i style="width:${Math.min(100,level*65+(unlock?15:0))}%"></i></div><small>${unlock?`Disponível desde ${req} • nível ${level.toFixed(1)}`:`Bloqueada até ${req}`}</small></div>`}).join('')}
function renderEconomy(){$("resources").innerHTML=[['💰','Tesouro',money(S.treasury),''],['🌾','Alimento',fmt(S.food),'estoque'],['⛓️','Ferro',fmt(S.iron),'estoque'],['🪵','Madeira',fmt(S.wood),'estoque'],['⚙️','Máquinas',fmt(S.machines),'unid.'],['⚡','Energia',fmt(S.energyStock),'estoque']].map(x=>`<div class="resource"><div class="r-icon">${x[0]}</div><div class="r-name">${x[1]}</div><b>${x[2]}</b><small>${x[3]}</small></div>`).join('');$("production").innerHTML=[['Agricultura',S.workforce.agro],['Manufatura',S.workforce.manufatura],['Indústria mecanizada',S.workforce.industria],['Navegação',S.workforce.navegacao],['Ciência',S.workforce.ciencia],['Serviços',S.workforce.servicos]].map(x=>bar(x[0],x[1],60)).join('');$("economyBars").innerHTML=[['Economia',S.economy],['Comércio',S.trade],['Infraestrutura',S.infrastructure],['Energia',S.energy],['Estabilidade',S.stability]].map(x=>bar(x[0],x[1],100)).join('')}
function bar(n,v,max){return `<div class="bar-row"><div class="bar-head"><span>${n}</span><b>${Math.round(v)}</b></div><div class="bar"><i style="width:${Math.min(100,v/max*100)}%"></i></div></div>`}
function renderMap(){
 document.querySelectorAll('.map-node.world').forEach(b=>b.classList.toggle('selected',b.dataset.region===S.selectedRegion));
 document.querySelectorAll('.map-mode').forEach(b=>b.classList.toggle('active',b.dataset.mapMode===(S.mapMode||'world')));
 const mode=S.mapMode||'world',id=S.selectedRegion||'upaon';
 const data={upaon:['🌴 Upaon-Açu','Território central',S.population,'Núcleo político, naval e urbano da campanha.'],brasil:['🌎 Brasil','Espaço continental',S.nations.brasil?.territory||35,'Grande mercado, recursos e profundidade estratégica.'],europa:['⚓ Europa','Potências europeias',Object.values(S.nations).filter(n=>n.region==='Europa').reduce((a,n)=>a+n.territory,0),'Centro de comércio, rivalidades, ciência e projeção oceânica.'],africa:['🌍 África','Rotas africanas',S.nations.magrebe?.territory||12,'Comércio costeiro, recursos e ligação com o interior.'],asia:['🏯 Ásia','China e Índia',75,'Grandes centros populacionais, científicos e produtivos.'],caribe:['🏝️ Caribe','Rotas insulares',S.nations.caribe?.territory||5,'Arquipélagos estratégicos e passagem atlântica.']}[id]||[];
 const modeText={world:'Visão global — continentes, macro-regiões e centros de poder.',atlantic:'Teatro Atlântico — concentre-se em Upaon-Açu, Caribe, África Ocidental, Brasil e Europa.',political:'Camada política — círculos mostram os principais centros de poder e relações.',routes:'Rotas estratégicas — linhas destacam conexões comerciais e navais.'}[mode];
 const modeEl=document.querySelector('.map-board');if(modeEl){modeEl.dataset.mode=mode}
 $("regionInfo").innerHTML=`<div class="map-info-head"><span class="eyebrow">${mode.toUpperCase()}</span><h3>${data[0]}</h3><div class="big">${id==='upaon'?fmt(data[2]):data[2]}</div><p class="desc">${data[3]}</p></div><div class="map-mode-note">${modeText}</div><div class="row"><span>Influência</span><b>${id==='upaon'?Math.round(S.diplomacyPower):Math.round(S.influence[id]||0)}</b></div><div class="row"><span>Tensão regional</span><b>${id==='upaon'?Math.round(100-S.stability):Math.round(regionTension(id))}</b></div><div class="row"><span>Rotas ativas</span><b>${Object.values(S.relations).filter(r=>r.trade>=25).length}</b></div>`;
}
function regionTension(r){const ns=Object.values(S.nations).filter(n=>n.region===r);return ns.length?ns.reduce((a,n)=>a+n.tension,0)/ns.length:0}
function renderSociety(){const city=S.cities.saoLuis;$("demography").innerHTML=[['População',fmt(S.population)],['Urbanização',Math.round(S.urban)+'%'],['Saúde',Math.round(S.health)],['Educação',Math.round(S.education)],['Estabilidade',Math.round(S.stability)],['São Luís',fmt(city.pop)]].map(x=>`<div class="row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$("workforce").innerHTML=Object.entries(S.workforce).map(([k,v])=>bar(k[0].toUpperCase()+k.slice(1),v,60)).join('');$("censusReport").innerHTML=S.censuses.at(-1)?`Ano ${S.censuses.at(-1).year}: <b>${fmt(S.censuses.at(-1).population)}</b> habitantes, ${S.censuses.at(-1).urban}% urbanos.`:"Nenhum censo.";drawChart()}
function renderMilitary(){$("militaryStats").innerHTML=[['Força militar',S.military],['Prontidão',S.readiness],['Tecnologia',S.technology],['Logística',S.infrastructure],['Guerras vencidas',S.warsWon],['Guerras perdidas',S.warsLost]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${typeof x[1]==='number'?Math.round(x[1]):x[1]}</b></div>`).join('');$("exerciseGrid").innerHTML=[{name:'Exercício terrestre',icon:'🪖',fn:'exerciseLand'},{name:'Exercício naval',icon:'⚓',fn:'exerciseNaval'},{name:'Exercício aéreo',icon:'✈️',fn:'exerciseAir'},{name:'Mobilização logística',icon:'📦',fn:'exerciseLog'}].map(x=>`<button class="action" data-ex="${x.fn}"><span class="icon">${x.icon}</span><span class="cat">1 AP</span><h3>${x.name}</h3><p>Melhora prontidão sem iniciar guerra.</p></button>`).join('');document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>exercise(b.dataset.ex))}
function exercise(type){if(S.actionsLeft<1)return toast('Sem AP.');S.actionsLeft--;S.readiness+=type==='exerciseLog'?6:8;S.military+=type==='exerciseNaval'?1.5:1;S.history.push({year:S.year,text:`${type.replace('exercise','')} realizado; prontidão elevada.`});clampAll();render();toast('Exercício concluído sem iniciar guerra.')}
function populateTargets(){const opts=Object.entries(S.nations).map(([id,n])=>`<option value="${id}">${n.flag} ${n.name}</option>`).join('');['attackTarget','spyTarget'].forEach(id=>{if($(id))$(id).innerHTML=opts});}
function strategicAttack(){const id=targetId(),n=S.nations[id],rel=S.relations[id];if(!n)return toast('Alvo inválido.');if(S.actionsLeft<2)return toast('Ataque exige 2 AP.');if(S.alliances.includes(id)||rel?.alliance==='alliance')return toast(`Você possui uma aliança com ${n.name}. Rompa a aliança antes de atacar.`);if(S.warStatus[id]==='war')return toast(`A guerra contra ${n.name} já está em andamento.`);if(S.warStatus[id]==='peace')S.warStatus[id]=null;S.actionsLeft-=2;S.warStatus[id]='war';n.tension=clamp(n.tension+25);const ours=S.military+S.tech.sistemas*2+S.tech.controle*1.5+S.readiness*.25+S.infrastructure*.15;const theirs=n.military+n.stability*.25+Math.random()*22;if(ours>theirs*1.15){n.military=Math.max(0,n.military-8);n.stability-=5;S.military-=2;S.economy-=2;S.diplomacyPower-=6;S.warsWon++;S.territory+=.15;S.warStatus[id]='victory';S.history.push({year:S.year,text:`Guerra contra ${n.name}: vitória estratégica; influência territorial ampliada.`});toast(`Vitória contra ${n.name}.`)}else{n.military=Math.max(0,n.military-3);S.military-=5;S.stability-=7;S.economy-=4;S.diplomacyPower-=8;S.warsLost++;S.warStatus[id]='war';S.history.push({year:S.year,text:`Guerra contra ${n.name}: ofensiva repelida.`});toast(`Ofensiva repelida por ${n.name}.`)}clampAll();render()}
function espionage(){if(S.actionsLeft<1)return toast('Sem AP.');const id=targetId(),n=S.nations[id];S.actionsLeft--;const intel=clamp(S.science*.45+S.tech.dados*4+S.tech.semfio*3+Math.random()*25);if(Math.random()*100<intel){S.science+=2;S.technology+=1;S.influence[id]=(S.influence[id]||0)+4;S.history.push({year:S.year,text:`Inteligência obtida sobre ${n.name}: forças e economia avaliadas.`});toast(`Informações obtidas sobre ${n.name}.`)}else{n.tension=clamp(n.tension+10);n.attitude-=6;S.diplomacyPower-=3;S.history.push({year:S.year,text:`Espionagem contra ${n.name} foi detectada.`});toast(`Operação detectada por ${n.name}.`)}clampAll();render()}
function treaty(type){if(S.actionsLeft<1)return toast('Sem AP.');const id=targetId(),n=S.nations[id],d=S.relations[id];S.actionsLeft--;if(type==='trade'){d.trade=clamp(d.trade+12);n.trade=clamp(n.trade+8);S.economy+=3;S.treasury+=6;n.tension=clamp(n.tension-6)}if(type==='science'){d.science+=8;S.science+=3;S.technology+=2;n.attitude=clamp(n.attitude+5,-100,100)}if(type==='peace'){d.trust=clamp(d.trust+12);n.tension=clamp(n.tension-15);n.attitude=clamp(n.attitude+10,-100,100);S.stability+=2;S.warStatus[id]='peace'}S.history.push({year:S.year,text:`Tratado ${type==='trade'?'comercial':type==='science'?'científico':'de não agressão'} firmado com ${n.name}.`});clampAll();render();toast(`Tratado firmado com ${n.name}.`)}
function alliance(){if(S.actionsLeft<2)return toast('Aliança exige 2 AP.');const id=targetId(),n=S.nations[id],d=S.relations[id];if(d.trust<25||n.attitude<15)return toast('Confiança insuficiente para uma aliança.');S.actionsLeft-=2;if(!S.alliances.includes(id))S.alliances.push(id);d.alliance='alliance';n.alliance='Upaon-Açu';n.tension=clamp(n.tension-12);S.diplomacyPower+=5;S.military+=2;S.history.push({year:S.year,text:`Aliança estratégica formada com ${n.name}.`});render();toast(`Aliança formada com ${n.name}.`)}
function tradeRoute(){if(S.actionsLeft<1)return toast('Sem AP.');const id=targetId(),n=S.nations[id];S.actionsLeft--;S.trade+=8;S.economy+=2;S.treasury+=10;S.influence[id]=(S.influence[id]||0)+5;n.attitude=clamp(n.attitude+3,-100,100);S.history.push({year:S.year,text:`Nova rota comercial com ${n.name}.`});render();toast(`Rota comercial aberta com ${n.name}.`)}
function doCensus(silent=false){S.censuses.push({year:S.year,population:S.population,urban:Math.round(S.urban),education:Math.round(S.education),health:Math.round(S.health)});if(!silent)toast('Censo registrado.')}
function randomEvent(){const pool=[['🌾 Colheita favorável','A produção de alimentos cresce e reduz pressões internas.',()=>{S.food+=10;S.stability+=2}],['🌊 Tempestade atlântica','Portos e comércio sofrem perdas temporárias.',()=>{S.trade-=3;S.infrastructure-=1}],['📚 Descoberta científica','Pesquisadores avançam uma técnica promissora.',()=>{S.science+=2;S.technology+=2}],['🧭 Navegadores estrangeiros','Uma potência estrangeira oferece uma oportunidade comercial.',()=>{S.trade+=4;S.diplomacyPower+=2}],['⚠️ Crise de abastecimento','A logística falha e parte dos estoques é consumida.',()=>{S.food-=7;S.stability-=3}],['🕊️ Aproximação diplomática','Uma potência reconsidera sua postura.',()=>{const ns=Object.values(S.nations);const n=ns[Math.floor(Math.random()*ns.length)];n.attitude=clamp(n.attitude+8,-100,100)}]];return pool[Math.floor(Math.random()*pool.length)]}
function nextRound(free=false){if(!free&&S.actionsLeft===5)return toast('Escolha pelo menos uma ação ou use “Passar sem ações”.');const names=[...S.selectedActions];const ev=randomEvent();ev[2]();const growth=.007+S.health*.00005+S.education*.000025;S.population*=1+growth;S.urban=clamp(S.urban+Math.max(.08,S.industry*.011+S.infrastructure*.003),0,96);S.economy=clamp(S.economy+S.industry*.015+S.education*.01-1);S.science=clamp(S.science+S.education*.018+S.technology*.006-.1);S.industry=clamp(S.industry+S.energy*.008-.06);S.technology=clamp(S.technology+S.science*.008);S.military=clamp(S.military-.04);S.readiness=clamp(S.readiness-1);S.infrastructure=clamp(S.infrastructure+S.industry*.004);S.health=clamp(S.health+S.education*.004-.02);S.stability=clamp(S.stability+(S.health>25?.1:-.2));S.food=clamp(S.food+S.workforce.agro*.25-S.population/70000,0,9999);S.wood=clamp(S.wood+S.workforce.agro*.08-S.infrastructure*.015,0,9999);S.iron=clamp(S.iron+S.workforce.minera*.18-S.industry*.02,0,9999);S.energyStock=clamp(S.energyStock+S.energy*.35-S.industry*.04,0,9999);S.treasury=Math.max(0,S.treasury+S.economy*.12+S.trade*.05-S.industry*.04);
 S.workforce.industria=clamp(S.workforce.industria+.14,0,48);S.workforce.agro=clamp(S.workforce.agro-.12,8,60);S.workforce.ciencia=clamp(S.workforce.ciencia+(S.education>40?.05:.01),0,20);S.workforce.servicos=clamp(S.workforce.servicos+.04,0,25);const c=S.cities.saoLuis;c.pop*=1+growth*1.2;c.industry=clamp(c.industry+S.industry*.01);c.infra=clamp(c.infra+S.infrastructure*.008);c.science=clamp(c.science+S.science*.005);c.education=clamp(c.education+S.education*.004);c.health=clamp(c.health+S.health*.004);
 Object.values(S.nations).forEach(n=>{n.economy=clamp(n.economy+(Math.random()-.35)*1.5);n.science=clamp(n.science+(Math.random()-.2)*1.2);n.stability=clamp(n.stability+(Math.random()-.5));n.military=clamp(n.military+(Math.random()-.35));if(n.tension>70)n.attitude-=1;}); Object.entries(S.warStatus).forEach(([id,status])=>{if(status!=='war')return;const n=S.nations[id];if(!n)return;n.tension=clamp(n.tension+2);if(Math.random()<.16){S.economy=clamp(S.economy-1.5);S.readiness=clamp(S.readiness-2);S.history.push({year:S.year,text:`Conflito prolongado com ${n.name}: desgaste logístico e econômico.`})}});Object.entries(S.relations).forEach(([id,r])=>{if(S.alliances.includes(id)){r.trust=clamp(r.trust+1);S.nations[id].tension=clamp(S.nations[id].tension-1)}});
 S.year++;S.round++;S.actionsLeft=5;S.selectedActions=[];S.history.push({year:S.year,text:`${ev[0]} — ${ev[1]}`});for(const m of milestones)if(m[0]===S.year)S.history.push({year:S.year,text:`${m[1]} — ${m[2]}`});S.lastGlobal=globalSnapshot();S.lastReport={actions:names.length?names:["Passagem livre — nenhuma ação direta"],free,event:ev[0],eventText:ev[1],population:S.population,economy:S.economy,science:S.science,industry:S.industry,military:S.military,technology:S.technology};clampAll();render();showReport()}
function globalSnapshot(){return{year:S.year,powers:Object.entries(S.nations).map(([id,n])=>({id,name:n.name,flag:n.flag,military:Math.round(n.military),economy:Math.round(n.economy),science:Math.round(n.science),stability:Math.round(n.stability),attitude:Math.round(n.attitude),tension:Math.round(n.tension),territory:Math.round(n.territory),alliance:n.alliance}))}}
function showReport(){const r=S.lastReport,g=S.lastGlobal||globalSnapshot();$("roundReport").innerHTML=`<h2>🌴 UPAON-AÇU — ROUND ${S.round}</h2><p class="muted">ANO ${S.year} • ${era()}</p><div class="card"><h3>Decisões executadas</h3><p>${r.actions.map(x=>'• '+x).join('<br>')}</p></div><div class="card"><h3>🎲 ${r.event}</h3><p class="muted">${r.eventText}</p></div><div class="report-grid">${Object.entries({População:fmt(r.population),Economia:Math.round(r.economy)+"/100",Ciência:Math.round(r.science)+"/100",Indústria:Math.round(r.industry)+"/100",Tecnologia:Math.round(r.technology)+"/100",Militar:Math.round(r.military)+"/100"}).map(([k,v])=>`<div class="report-box"><small>${k}</small><b>${v}</b></div>`).join('')}</div><div class="card"><h3>🌎 Equilíbrio de poder</h3>${g.powers.sort((a,b)=>b.military-a.military).map(n=>`<div class="row"><span>${n.flag} ${n.name} ${n.alliance?'🤝':''}</span><b>Mil ${n.military} • Econ ${n.economy} • Ciência ${n.science} • Tensão ${n.tension}</b></div>`).join('')}</div><p class="muted">Você recebeu 5 novos pontos de ação. O próximo ano só avança quando você decidir.</p>`;$("reportModal").classList.remove('hidden')}
function renderDiplomacy(){$("diplomacyGrid").innerHTML=Object.entries(S.nations).map(([id,n])=>{const d=S.relations[id],war=S.warStatus[id]==='war',ally=S.alliances.includes(id);return `<div class="dip"><h3>${n.flag} ${n.name}</h3><div class="relation">${war?'⚔️ EM GUERRA':ally?'🤝 ALIADO':n.attitude>=30?'🟢 amistoso':n.attitude<=-20?'🔴 hostil':'🟡 competitivo'}</div><div class="row"><span>Atitude</span><b>${Math.round(n.attitude)}</b></div><div class="row"><span>Confiança</span><b>${Math.round(d.trust)}</b></div><div class="row"><span>Comércio</span><b>${Math.round(d.trade)}</b></div><div class="row"><span>Influência</span><b>${Math.round(S.influence[id]||0)}</b></div><div class="row"><span>Força</span><b>${Math.round(n.military)}</b></div></div>`}).join('')}
function renderTimeline(){$("timeline").innerHTML=S.history.slice().reverse().slice(0,80).map(e=>`<div class="event"><div class="date">${e.year}</div><div class="txt">${e.text}</div></div>`).join('')}
function drawChart(){const c=$("chart");if(!c)return;const ctx=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth||800,h=260;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const hist=S.censuses.length?S.censuses.map(x=>x.population):[S.population];if(hist.length<2)hist.unshift(S.population*.92);const min=Math.min(...hist),max=Math.max(...hist);ctx.strokeStyle='#214737';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=35+i*60;ctx.beginPath();ctx.moveTo(20,y);ctx.lineTo(w-20,y);ctx.stroke()}ctx.strokeStyle='#67e09e';ctx.lineWidth=3;ctx.beginPath();hist.forEach((v,i)=>{const x=20+i*(w-40)/(hist.length-1),y=225-(v-min)/Math.max(1,max-min)*180;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#91b1a2';ctx.font='11px system-ui';ctx.fillText('População — censos registrados',20,18);ctx.fillText(fmt(min),20,248);ctx.fillText(fmt(max),20,32)}
function clampAll(){['stability','economy','science','industry','technology','military','diplomacyPower','education','health','energy','infrastructure','readiness','urban','trade'].forEach(k=>S[k]=clamp(S[k]));S.population=Math.max(100,S.population);S.treasury=Math.max(0,S.treasury);['food','iron','wood','machines','energyStock'].forEach(k=>S[k]=Math.max(0,S[k]));Object.values(S.nations).forEach(n=>{n.tension=clamp(n.tension);n.military=clamp(n.military);n.economy=clamp(n.economy);n.science=clamp(n.science);n.stability=clamp(n.stability);n.attitude=clamp(n.attitude,-100,100)});Object.values(S.relations||{}).forEach(r=>{r.trust=clamp(r.trust);r.trade=clamp(r.trade);r.science=clamp(r.science)})}
function save(){localStorage.setItem(KEY,JSON.stringify(S));$("saveState").textContent='● salvo agora';toast('Campanha V5 salva neste navegador.')}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!x)return toast('Nenhum save V5 encontrado.');S=Object.assign(structuredClone(initial),x);S.nations=Object.assign(structuredClone(nationTemplate),x.nations||{});const oldRelations=(x.relations&&typeof x.relations==='object')?x.relations:((x.diplomacy&&typeof x.diplomacy==='object')?x.diplomacy:{});S.relations=Object.assign(structuredClone(initial.relations),oldRelations);S.diplomacyPower=Number.isFinite(+x.diplomacyPower)?+x.diplomacyPower:(typeof x.diplomacy==='number'?+x.diplomacy:18);S.selectedRegion=x.selectedRegion||'upaon';S.mapMode=x.mapMode||'world';S.actionsLeft=Number.isFinite(+S.actionsLeft)?clamp(+S.actionsLeft,0,5):5;S.selectedActions=Array.isArray(S.selectedActions)?S.selectedActions:[];S.alliances=Array.isArray(S.alliances)?S.alliances:[];S.influence=x.influence||{};S.warStatus=x.warStatus||{};S.censuses=Array.isArray(S.censuses)?S.censuses:[];S.history=Array.isArray(S.history)?S.history:[];$("startScreen").classList.add('hidden');clampAll();render();toast('Campanha carregada.') }catch(e){console.error(e);toast('Save inválido.')}}
function newGame(){if(confirm('Começar uma nova campanha V5?')){$("startScreen").classList.remove('hidden');S=structuredClone(initial);S.actionsLeft=5;S.diplomacyPower=18;setupPreview();render();}}
function toast(t){const x=$("toast");x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2300)}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel-page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='populacao')drawChart()});
$("nextRound").onclick=()=>nextRound(false);$("freeRound").onclick=()=>nextRound(true);$("attackBtn").onclick=strategicAttack;$("spyBtn").onclick=espionage;$("censusBtn").onclick=()=>doCensus(false);$("tradeTreaty").onclick=()=>treaty('trade');$("scienceTreaty").onclick=()=>treaty('science');$("nonAggression").onclick=()=>treaty('peace');$("saveBtn").onclick=save;$("loadBtn").onclick=load;$("newBtn").onclick=newGame;$("reportBtn").onclick=()=>{if(S.lastReport)showReport();else toast('Ainda não há relatório.')};$("closeModal").onclick=()=>$("reportModal").classList.add('hidden');$("reportModal").onclick=e=>{if(e.target.id==='reportModal')e.currentTarget.classList.add('hidden')};
if($("allianceBtn"))$("allianceBtn").onclick=alliance;if($("tradeRouteBtn"))$("tradeRouteBtn").onclick=tradeRoute;
document.querySelectorAll('.map-node.world').forEach(b=>b.onclick=()=>{S.selectedRegion=b.dataset.region;renderMap()});document.querySelectorAll('.map-mode').forEach(b=>b.onclick=()=>{S.mapMode=b.dataset.mapMode;renderMap()});
window.addEventListener('resize',drawChart);
render();
})();
