(() => {
"use strict";
const KEY="upaon-acu-v10";const LEGACY_KEY="upaon-acu-v9";
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0));
const fmt=n=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(Math.max(0,n));
const money=n=>"¤ "+new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(Math.max(0,n));
const $=id=>document.getElementById(id);

const START_CONTEXTS={
 upaon:["Upaon-Açu","Núcleo atlântico, posição marítima e forte potencial de centralização."],brasil:["Brasil","Grande espaço territorial, recursos naturais e múltiplas fronteiras."],amazonia:["Amazônia","Rede fluvial extensa, baixa densidade e enorme fronteira de recursos."],nordeste:["Nordeste Atlântico","Litoral comercial, agricultura e portos estratégicos."],caribe:["Caribe","Arquipélago estratégico entre as Américas e as rotas atlânticas."],iberia:["Península Ibérica","Navegação avançada, Estados centralizados e rivalidades continentais."],africa:["África Ocidental","Rios, comércio e cidades costeiras conectam o interior ao Atlântico."],india:["Índia","Grande população, comércio oceânico e tradição científica."],china:["China","Alta escala populacional, administração e capacidade produtiva."]};

const nationTemplate={
 portugal:{name:"Portugal",flag:"🇵🇹",region:"Europa",military:30,economy:50,science:42,stability:68,attitude:18,trade:18,tension:15,territory:9,alliance:null},
 espanha:{name:"Espanha",flag:"🇪🇸",region:"Europa",military:34,economy:52,science:40,stability:64,attitude:10,trade:10,tension:20,territory:10,alliance:null},
 franca:{name:"França",flag:"🇫🇷",region:"Europa",military:38,economy:56,science:58,stability:65,attitude:24,trade:12,tension:8,territory:14,alliance:null},
 holanda:{name:"Países Baixos",flag:"🇳🇱",region:"Europa",military:26,economy:62,science:50,stability:70,attitude:22,trade:20,tension:10,territory:7,alliance:null},
 inglaterra:{name:"Inglaterra",flag:"🇬🇧",region:"Europa",military:43,economy:65,science:55,stability:67,attitude:18,trade:15,tension:12,territory:12,alliance:null},
 china:{name:"China",flag:"🇨🇳",region:"Ásia",military:46,economy:72,science:48,stability:72,attitude:10,trade:5,tension:3,territory:45,alliance:null},
 india:{name:"Índia",flag:"🇮🇳",region:"Ásia",military:32,economy:60,science:52,stability:62,attitude:14,trade:8,tension:4,territory:30,alliance:null},
 magrebe:{name:"Magrebe",flag:"🌍",region:"África",military:25,economy:40,science:35,stability:60,attitude:26,trade:11,tension:5,territory:12,alliance:null},
 caribe:{name:"Confederação Caribenha",flag:"🏝️",region:"Caribe",military:20,economy:38,science:30,stability:58,attitude:32,trade:14,tension:7,territory:5,alliance:null},
 brasil:{name:"Estados do Brasil",flag:"🌎",region:"Américas",military:28,economy:45,science:30,stability:55,attitude:15,trade:9,tension:10,territory:35,alliance:null}
};

const PEOPLE_PROFILES={
upaonense:{name:"Povo Upaonense",culture:"Civilização insular atlântica",family:"Brasil • Maranhão",pop:1,food:1.05,wood:1.05,military:0,science:0,industry:0,education:1,urban:0,traits:["Navegação costeira","Pesca e rios","Centralização insular"],techStart:{agricultura:1,navegacao:1,ceramica:1},techBonus:{navegacao:.2,naval:.15},regional:"Atlântico Sul"},
tupinamba:{name:"Tupinambá",culture:"Povo tupi costeiro e marítimo",family:"Brasil • litoral atlântico",pop:1.25,food:1.12,wood:1.12,military:2,science:1,industry:-1,education:1,urban:-1,traits:["Agricultura tropical","Canoas e navegação","Redes de alianças"],techStart:{agricultura:1,navegacao:1,ceramica:1,botanica:1},techBonus:{navegacao:.25,agricultura:.15},regional:"Costa do Brasil"},
guarani:{name:"Guarani",culture:"Povos guarani de redes fluviais e agrícolas",family:"Brasil • Sul e interior",pop:1.15,food:1.18,wood:1.04,military:1,science:1,industry:-1,education:1,urban:-1,traits:["Agricultura","Redes fluviais","Conhecimento botânico"],techStart:{agricultura:1,botanica:1,navegacao:1},techBonus:{agricultura:.2,botanica:.25},regional:"Bacia Platina"},
marajoara:{name:"Povo Marajoara",culture:"Sociedade amazônica de engenharia hidráulica e cerâmica",family:"Brasil • Marajó",pop:1.05,food:1.14,wood:1.08,military:1,science:2,industry:0,education:2,urban:1,traits:["Cerâmica","Manejo de águas","Agricultura de várzea"],techStart:{agricultura:1,ceramica:1,engenharia_hidraulica:1,botanica:1},techBonus:{ceramica:.3,engenharia_hidraulica:.35},regional:"Amazônia"},
macroje:{name:"Povo Macro-Jê",culture:"Povos do interior com forte adaptação terrestre e florestal",family:"Brasil • interior",pop:1.1,food:1.08,wood:1.12,military:2,science:1,industry:0,education:1,urban:-2,traits:["Manejo florestal","Caça e agricultura","Adaptação territorial"],techStart:{agricultura:1,botanica:1,manejo_florestal:1},techBonus:{manejo_florestal:.3,agricultura:.1},regional:"Interior brasileiro"},
guaicuru:{name:"Povo Guaicuru",culture:"Sociedade de mobilidade terrestre",family:"Brasil • Centro-Oeste e Chaco",pop:.85,food:1.05,wood:1.02,military:5,science:1,industry:0,education:1,urban:-2,traits:["Mobilidade","Guerra territorial","Conhecimento do terreno"],techStart:{agricultura:1,manejo_florestal:1},techBonus:{guerra:.35,logistica:.2},regional:"Centro-Oeste"},
africano:{name:"Reino Atlântico Africano",culture:"Monarquia comercial atlântica",family:"África • oeste",pop:2.2,food:1.25,wood:1.1,military:5,science:2,industry:2,education:2,urban:3,traits:["Comércio regional","Metalurgia","Cidades e portos"],techStart:{agricultura:1,metalurgia:1,navegacao:1},techBonus:{metalurgia:.25,navegacao:.15},regional:"África Ocidental"},
sahel:{name:"Reino do Sahel",culture:"Estado caravanista e comercial",family:"África • Sahel",pop:2,food:1.08,wood:.92,military:5,science:2,industry:1,education:3,urban:3,traits:["Caravanas","Metalurgia","Administração"],techStart:{agricultura:1,metalurgia:1,escrita:1},techBonus:{metalurgia:.2,logistica:.3},regional:"Sahel"},
swahili:{name:"Cidades Suaílis",culture:"Rede mercantil do Índico africano",family:"África • costa oriental",pop:1.7,food:1.12,wood:1,military:3,science:3,industry:2,education:3,urban:4,traits:["Comércio oceânico","Portos","Astronomia náutica"],techStart:{agricultura:1,navegacao:1,escrita:1},techBonus:{navegacao:.3,astronomia:.2},regional:"Oceano Índico"},
iberico:{name:"Reino Ibérico",culture:"Estado marítimo europeu",family:"Europa • Ibéria",pop:3,food:1,wood:.9,military:10,science:6,industry:5,education:5,urban:8,traits:["Navegação oceânica","Administração monárquica","Estaleiros"],techStart:{agricultura:1,escrita:1,metalurgia:1,navegacao:1,cartografia:1},techBonus:{navegacao:.3,naval:.2,cartografia:.3},regional:"Europa Ocidental"},
franca:{name:"Reino Franco",culture:"Monarquia continental europeia",family:"Europa • França",pop:2.8,food:1,wood:.95,military:8,science:7,industry:4,education:5,urban:7,traits:["Administração","Artes e ciência","Engenharia militar"],techStart:{agricultura:1,escrita:1,metalurgia:1},techBonus:{mecanica:.15,medicina:.2},regional:"Europa Ocidental"},
inglesa:{name:"Reino Inglês",culture:"Potência marítima em formação",family:"Europa • Ilhas Britânicas",pop:2.5,food:1,wood:.95,military:9,science:7,industry:5,education:5,urban:7,traits:["Marinha","Comércio","Construção naval"],techStart:{agricultura:1,escrita:1,metalurgia:1,navegacao:1},techBonus:{naval:.3,mecanica:.2},regional:"Atlântico Norte"},
holandesa:{name:"Províncias Neerlandesas",culture:"República mercantil marítima",family:"Europa • Países Baixos",pop:1.8,food:.95,wood:.9,military:5,science:8,industry:6,education:6,urban:10,traits:["Comércio financeiro","Cartografia","Engenharia hidráulica"],techStart:{agricultura:1,escrita:1,navegacao:1,cartografia:1},techBonus:{cartografia:.35,engenharia_hidraulica:.25},regional:"Europa do Norte"},
norteamericano:{name:"Povos da América do Norte",culture:"Confederação continental diversificada",family:"Américas • Norte",pop:1.5,food:1.1,wood:1.2,military:3,science:2,industry:0,education:2,urban:0,traits:["Manejo florestal","Confederações","Agricultura regional"],techStart:{agricultura:1,manejo_florestal:1},techBonus:{manejo_florestal:.25,agricultura:.12},regional:"América do Norte"},
asteca:{name:"Mexicas",culture:"Estado mesoamericano urbano e tributário",family:"Américas • Central",pop:4,food:1.3,wood:1,military:7,science:5,industry:2,education:4,urban:12,traits:["Cidades","Agricultura intensiva","Administração tributária"],techStart:{agricultura:1,ceramica:1,astronomia:1,escrita:1},techBonus:{agricultura:.25,astronomia:.25,administracao:.2},regional:"Mesoamérica"},
maia:{name:"Cidades Maias",culture:"Civilização mesoamericana de conhecimento astronômico",family:"Américas • Central",pop:3.2,food:1.2,wood:1,military:4,science:7,industry:1,education:6,urban:10,traits:["Astronomia","Matemática","Cidades-Estado"],techStart:{agricultura:1,escrita:1,astronomia:1,matematica:1},techBonus:{astronomia:.4,matematica:.35},regional:"Mesoamérica"},
inca:{name:"Tawantinsuyu",culture:"Estado andino de estradas e administração",family:"Américas • Sul",pop:4.5,food:1.3,wood:.85,military:7,science:4,industry:2,education:4,urban:9,traits:["Estradas","Agricultura de altitude","Administração"],techStart:{agricultura:1,engenharia:1,administracao:1},techBonus:{engenharia:.3,agricultura:.2,logistica:.25},regional:"Andes"},
caribenho:{name:"Povos Caribenhos",culture:"Sociedades insulares e marítimas do Caribe",family:"Américas • Caribe",pop:1.1,food:1.12,wood:1.1,military:2,science:2,industry:0,education:2,urban:1,traits:["Canoas oceânicas","Ilhas","Comércio marítimo"],techStart:{agricultura:1,navegacao:1,ceramica:1},techBonus:{navegacao:.35,naval:.1},regional:"Caribe"},
indico:{name:"Reino do Índico",culture:"Potência comercial do oceano Índico",family:"Ásia • Sul",pop:6,food:1.2,wood:.95,military:6,science:8,industry:4,education:8,urban:10,traits:["Comércio oceânico","Matemática","Metalurgia e tecidos"],techStart:{agricultura:1,escrita:1,metalurgia:1,navegacao:1,matematica:1},techBonus:{matematica:.3,metalurgia:.2,navegacao:.2},regional:"Índico"},
sinico:{name:"Estado Sínico",culture:"Estado burocrático e produtivo do leste asiático",family:"Ásia • Leste",pop:8,food:1.35,wood:.9,military:9,science:7,industry:8,education:10,urban:12,traits:["Burocracia","Produção em escala","Papel e pólvora"],techStart:{agricultura:1,escrita:1,metalurgia:1,engenharia:1,matematica:1},techBonus:{administracao:.35,metalurgia:.25,engenharia:.25},regional:"Leste Asiático"},
japonesa:{name:"Japão",culture:"Estado insular de tradição guerreira e artesanal",family:"Ásia • Japão",pop:2,food:1.15,wood:1,military:7,science:4,industry:3,education:5,urban:6,traits:["Artesanato de precisão","Guerra insular","Navegação costeira"],techStart:{agricultura:1,metalurgia:1,navegacao:1},techBonus:{metalurgia:.3,mecanica:.15},regional:"Pacífico Ocidental"},
persa:{name:"Reino Persa",culture:"Estado de planaltos e rotas continentais",family:"Ásia • Oeste",pop:3.5,food:1.05,wood:.85,military:7,science:5,industry:2,education:5,urban:7,traits:["Estradas","Administração","Astronomia"],techStart:{agricultura:1,escrita:1,astronomia:1,administracao:1},techBonus:{logistica:.3,astronomia:.25},regional:"Oriente Médio"},
polinesia:{name:"Confederação Polinésia",culture:"Povos navegadores do Pacífico",family:"Oceania • Polinésia",pop:.9,food:1.05,wood:1.15,military:2,science:2,industry:-1,education:2,urban:-2,traits:["Navegação oceânica","Ilhas","Cartografia oral"],techStart:{agricultura:1,navegacao:1},techBonus:{navegacao:.45,cartografia:.2},regional:"Pacífico"},
melanesia:{name:"Povos Melanésios",culture:"Sociedades insulares e marítimas",family:"Oceania • Melanésia",pop:.8,food:1.05,wood:1.18,military:2,science:1,industry:-1,education:1,urban:-2,traits:["Navegação regional","Manejo florestal","Pesca"],techStart:{agricultura:1,navegacao:1,manejo_florestal:1},techBonus:{manejo_florestal:.25,navegacao:.25},regional:"Pacífico"},
australiano:{name:"Povos da Austrália",culture:"Sociedades de adaptação ecológica continental",family:"Oceania • Austrália",pop:.7,food:1,wood:1.05,military:2,science:2,industry:-1,education:2,urban:-3,traits:["Conhecimento ecológico","Mobilidade","Manejo territorial"],techStart:{manejo_florestal:1,botanica:1},techBonus:{botanica:.3,manejo_florestal:.35},regional:"Austrália"},
custom:{name:"Povo personalizado",culture:"Civilização emergente",family:"Escolha livre",pop:1,food:1,wood:1,military:0,science:0,industry:0,education:0,urban:0,traits:["Identidade própria","Adaptação","Escolha do jogador"],techStart:{},techBonus:{},regional:"Indefinido"}
};

const initial={year:1460,round:1,actionsLeft:5,selectedActions:[],population:18000,urban:7,territory:1,stability:72,economy:38,science:8,industry:12,technology:5,military:7,diplomacyPower:18,education:9,health:8,energy:3,infrastructure:8,readiness:18,treasury:120,food:100,iron:22,wood:70,machines:4,energyStock:15,trade:20,
 lastReport:null,lastGlobal:null,censuses:[],history:[{year:1460,text:"Fundação e centralização de Upaon-Açu."}],warStatus:{},alliances:[],sanctions:[],influence:{},warsWon:0,warsLost:0,
 tech:{mecanica:0,quimica:0,medicina:0,microbiologia:0,eletricidade:0,automacao:0,controle:0,naval:0,submersiveis:0,aeronautica:0,aerodinamica:0,navegacao:0,computacao:0,programacao:0,dados:0,semfio:0,sistemas:0,industria:0},
 selectedRegion:"upaon",mapMode:"world",researchPoints:3,projects:{ships:0,generators:0,aircraft:0,computers:0},institutions:[],territories:{upaon:{name:"Upaon-Açu",control:100,development:25,resource:"madeira • pesca • porto"}},
 workforce:{agro:48,pesca:12,construcao:8,minera:4,manufatura:15,industria:3,navegacao:3,servicos:4,ciencia:1,outros:2},
 economyModel:{prices:{food:1,wood:1,iron:1,machines:4,energy:2},lastFlow:{food:0,wood:0,iron:0,machines:0,energy:0,treasury:0},shortages:[],surplus:[]},
 resourcePotential:{food:1.1,wood:1.1,iron:1,energy:1},
 cities:{saoLuis:{name:"São Luís",pop:12000,industry:8,infra:14,science:8,port:20,education:10,health:8}},
 nations:structuredClone(nationTemplate),
 relations:Object.fromEntries(Object.entries(nationTemplate).map(([k,n])=>[k,{name:n.name,trust:20,trade:n.trade,tension:n.tension,science:3,alliance:null}]))
};
let S=structuredClone(initial);

const actions=[
{id:"admin",icon:"🏛️",cat:"Estado",name:"Reforma administrativa",desc:"Fortalece governança, arrecadação e infraestrutura pública.",cost:"¤ −8 • 1 AP",apply(){S.stability+=5;S.infrastructure+=2;S.economy+=1;S.treasury-=8}},
{id:"edu",icon:"🎓",cat:"Educação",name:"Expandir educação",desc:"Forma professores, técnicos e futuros pesquisadores.",cost:"¤ −10 • 1 AP",apply(){S.education+=6;S.science+=2;S.treasury-=10}},
{id:"science",icon:"🔬",cat:"Ciência",name:"Instituto científico",desc:"Financia química, física, medicina e engenharia.",cost:"¤ −12 • 1 AP",apply(){S.science+=6;S.technology+=2;S.researchPoints+=2;S.treasury-=12}},
{id:"industry",icon:"🏭",cat:"Indústria",name:"Complexo industrial",desc:"Amplia máquinas, manufatura e produção nacional.",cost:"Fe −4 • ¤ −15 • 2 AP",ap:2,apply(){S.industry+=7;S.economy+=2;S.infrastructure+=2;S.iron-=4;S.machines+=1;S.treasury-=15;S.workforce.industria+=2;S.workforce.agro-=2}},
{id:"energy",icon:"⚡",cat:"Energia",name:"Programa energético",desc:"Aumenta geração e capacidade industrial.",cost:"Madeira −6 • ¤ −10 • 1 AP",apply(){S.energy+=7;S.industry+=2;S.infrastructure+=3;S.wood-=6;S.energyStock+=12;S.treasury-=10}},
{id:"health",icon:"🏥",cat:"Saúde",name:"Campanha sanitária",desc:"Saneamento e medicina elevam sobrevivência e estabilidade.",cost:"¤ −10 • 1 AP",apply(){S.health+=7;S.stability+=2;S.population*=1.004;S.treasury-=10}},
{id:"transport",icon:"🚂",cat:"Transporte",name:"Rede de transporte",desc:"Estradas, portos e vias internas conectam mercados.",cost:"Madeira −8 • ¤ −12 • 1 AP",apply(){S.infrastructure+=8;S.economy+=4;S.urban+=1;S.wood-=8;S.treasury-=12}},
{id:"naval",icon:"⚓",cat:"Naval",name:"Programa naval",desc:"Estaleiros ampliam comércio, projeção e defesa marítima.",cost:"Madeira −10 • Fe −3 • 1 AP",apply(){S.military+=2;S.infrastructure+=3;S.diplomacyPower+=2;S.tech.naval+=1;S.economy+=2;S.wood-=10;S.iron-=3}},
{id:"aero",icon:"✈️",cat:"Aeronáutica",name:"Pesquisa aeronáutica",desc:"Desenvolve aerostatos, aerodinâmica e voo experimental.",cost:"¤ −14 • 1 AP",apply(){S.science+=3;S.technology+=4;S.tech.aeronautica+=1;S.tech.aerodinamica+=.5;S.industry+=2;S.treasury-=14}},
{id:"compute",icon:"💻",cat:"Computação",name:"Laboratório de informação",desc:"Cálculo, codificação, memória e processamento.",cost:"¤ −15 • 2 AP",ap:2,apply(){S.science+=3;S.technology+=5;S.tech.computacao+=1;S.tech.dados+=1;S.tech.programacao+=.5;S.treasury-=15}},
{id:"mil",icon:"🪖",cat:"Militar",name:"Fortalecimento militar",desc:"Treinamento, logística e engenharia aumentam prontidão.",cost:"¤ −12 • Alimento −4 • 1 AP",apply(){S.military+=5;S.readiness+=8;S.treasury-=12;S.food-=4}},
{id:"dip",icon:"🌎",cat:"Diplomacia",name:"Missão diplomática",desc:"Amplia confiança, comércio e cooperação científica.",cost:"¤ −5 • 1 AP",apply(){S.diplomacyPower+=7;S.economy+=3;S.treasury-=5;Object.values(S.relations).forEach(x=>x.trust=clamp(x.trust+2))}},
{id:"trade",icon:"🤝",cat:"Economia",name:"Acordo comercial",desc:"Gera receita e aumenta rotas comerciais.",cost:"¤ −3 • 1 AP",apply(){S.economy+=4;S.trade+=7;S.diplomacyPower+=2;S.treasury-=3}},
{id:"census",icon:"📋",cat:"Estado",name:"Censo nacional",desc:"Registra população e melhora a capacidade administrativa.",cost:"Estabilidade −1 • 1 AP",apply(){doCensus(true);S.stability-=1}},
{id:"resources",icon:"⛏️",cat:"Recursos",name:"Expedição mineral",desc:"Procura ferro, madeira e matérias-primas.",cost:"¤ −7 • 1 AP",apply(){S.iron+=7+Math.random()*4;S.wood+=8;S.treasury-=7;S.industry+=1}},
{id:"urban",icon:"🏙️",cat:"Cidades",name:"Plano urbano",desc:"Habitação e infraestrutura aceleram urbanização.",cost:"¤ −9 • 1 AP",apply(){S.infrastructure+=5;S.urban+=3;S.treasury-=9;S.cities.saoLuis.infra+=5}},
{id:"influence",icon:"🕸️",cat:"Estratégia",name:"Rede de influência",desc:"Financia presença comercial e política em uma potência.",cost:"¤ −6 • 1 AP",apply(){const id=targetId();const d=S.relations[id],n=S.nations[id];d.trust=clamp(d.trust+7);n.attitude=clamp(n.attitude+4,-100,100);S.influence[id]=(S.influence[id]||0)+10;S.treasury-=6;S.diplomacyPower+=4}},
{id:"fort",icon:"🧱",cat:"Defesa",name:"Fortificações estratégicas",desc:"Defende portos e aumenta a capacidade de resistir a invasões.",cost:"Fe −3 • ¤ −10 • 1 AP",apply(){S.military+=3;S.readiness+=5;S.infrastructure+=2;S.iron-=3;S.treasury-=10}},
{id:"intelligence",icon:"🛰️",cat:"Inteligência",name:"Serviço de inteligência",desc:"Melhora contraespionagem e leitura do equilíbrio internacional.",cost:"¤ −8 • 1 AP",apply(){S.science+=2;S.technology+=2;S.readiness+=2;S.treasury-=8}},
{id:"ship",icon:"⛵",cat:"Projeto",name:"Construir navio",desc:"Aplica engenharia naval, materiais e navegação à construção de uma embarcação.",cost:"Madeira −14 • Fe −6 • 2 AP",ap:2,techReq:["engenharia_naval","navegacao"],apply(){S.wood-=14;S.iron-=6;S.military+=2;S.trade+=6;S.infrastructure+=2;S.projects.ships++}},
{id:"generator",icon:"⚡",cat:"Projeto",name:"Instalar gerador elétrico",desc:"Converte pesquisa em eletricidade utilizável.",cost:"Fe −5 • ¤ −18 • 2 AP",ap:2,techReq:["eletricidade","eletromagnetismo","materiais"],apply(){S.iron-=5;S.treasury-=18;S.energy+=7;S.energyStock+=18;S.industry+=3;S.projects.generators++}},
{id:"aircraft",icon:"🛩️",cat:"Projeto",name:"Construir aeronave",desc:"Projeto de voo motorizado baseado em aerodinâmica e combustão.",cost:"Máquinas −1 • ¤ −25 • 2 AP",ap:2,techReq:["aeronautica","aerodinamica","combustao"],apply(){S.machines=Math.max(0,S.machines-1);S.treasury-=25;S.military+=4;S.science+=2;S.projects.aircraft++}},
{id:"computer",icon:"🖥️",cat:"Projeto",name:"Construir computador",desc:"Protótipo de processamento automático de informação.",cost:"Máquinas −2 • ¤ −30 • 2 AP",ap:2,techReq:["computacao","programacao"],apply(){S.machines=Math.max(0,S.machines-2);S.treasury-=30;S.science+=4;S.technology+=3;S.projects.computers++}}
];

const tech=[
{id:"fogo",name:"Domínio do fogo",desc:"Uso controlado do fogo para calor, proteção, processamento de alimentos e transformação de materiais.",year:-100000,era:"Conhecimentos ancestrais",prereq:[],unlock:"Cozimento, conservação e processos térmicos básicos.",historical:"Conhecimento humano muito antigo; a data é deliberadamente aproximada."},
{id:"ferramentas_pedra",name:"Ferramentas de pedra",desc:"Lascamento, polimento e seleção de pedras para caça, corte, raspagem e trabalho da madeira.",year:-300000,era:"Conhecimentos ancestrais",prereq:[],unlock:"Caça, coleta, corte de madeira e construção simples.",historical:"Tecnologias líticas antecedem a agricultura por dezenas de milhares de anos."},
{id:"pesca",name:"Pesca especializada",desc:"Anzóis, redes, armadilhas e técnicas de pesca adaptadas aos ambientes locais.",year:-12000,era:"Caçadores e coletores",prereq:["ferramentas_pedra"],unlock:"Produção alimentar costeira e fluvial."},
{id:"cordas_fibras",name:"Fibras, cordas e trançados",desc:"Processamento de fibras vegetais para cordas, redes, cestos e amarrações.",year:-12000,era:"Caçadores e coletores",prereq:["ferramentas_pedra"],unlock:"Redes, cestos, armadilhas e melhor transporte de cargas."},
{id:"canoas",name:"Canoas e embarcações simples",desc:"Construção de embarcações leves usando madeira, fibras e técnicas de amarração.",year:-10000,era:"Caçadores e coletores",prereq:["ferramentas_pedra","cordas_fibras"],unlock:"Pesca ampliada, travessias e navegação regional."},
{id:"manejo_plantas",name:"Manejo de plantas",desc:"Seleção, propagação e manejo intencional de plantas úteis antes e durante a domesticação plena.",year:-12000,era:"Transição neolítica",prereq:["fogo"],unlock:"Base para horticultura e agricultura regional.",historical:"Nem toda sociedade passou diretamente de coleta para agricultura; houve múltiplos caminhos."},
{id:"domesticacao",name:"Domesticação de plantas e animais",desc:"Seleção deliberada de espécies e rebanhos para características úteis.",year:-10000,era:"Transição neolítica",prereq:["manejo_plantas"],unlock:"Horticultura, criação de animais e maior previsibilidade alimentar."},
{id:"sedentarismo",name:"Aldeias sedentárias",desc:"Ocupação mais permanente de lugares favoráveis, com armazenamento e estruturas comunitárias.",year:-9000,era:"Transição neolítica",prereq:["manejo_plantas","ceramica"],unlock:"Maior população, armazenamento e especialização do trabalho."},
{id:"tecelagem",name:"Fiação e tecelagem",desc:"Transformação de fibras em fios, cordões e tecidos para vestuário, redes e transporte.",year:-7000,era:"Neolítico",prereq:["cordas_fibras"],unlock:"Tecidos, velas e melhoria de equipamentos cotidianos."},
{id:"irrigacao",name:"Irrigação e manejo de águas",desc:"Canais, açudes, terraços e outras formas de controlar água para produção e ocupação.",year:-6000,era:"Neolítico",prereq:["agricultura","sedentarismo"],unlock:"Maior produtividade agrícola e resiliência hídrica."},
{id:"metalurgia_cobre",name:"Metalurgia do cobre",desc:"Extração, aquecimento e conformação inicial do cobre e de minerais metálicos.",year:-5000,era:"Metalurgia inicial",prereq:["fogo","ceramica"],unlock:"Ferramentas e ornamentos metálicos iniciais."},
{id:"bronze",name:"Bronze",desc:"Ligas de cobre com estanho ou outros componentes, com fundição e trabalho mais controlados.",year:-3300,era:"Metalurgia inicial",prereq:["metalurgia_cobre"],unlock:"Ferramentas, armas e objetos metálicos mais resistentes."},
{id:"ferro",name:"Metalurgia do ferro",desc:"Redução e forjamento de ferro em diferentes tradições metalúrgicas.",year:-1200,era:"Metalurgia avançada",prereq:["metalurgia_cobre","bronze"],unlock:"Ferramentas, armas e estruturas de ferro."},
{id:"agricultura",name:"Agricultura",desc:"Cultivo sistemático de plantas domesticadas ou manejadas, com técnicas regionais diversas.",year:-9000,era:"Neolítico",prereq:["manejo_plantas"],historical:"As datas e trajetórias variam muito entre regiões; não é uma invenção única.",unlock:"Expansão populacional, excedentes e especialização."},
{id:"ceramica",name:"Cerâmica",desc:"Queima controlada de argilas para recipientes, armazenamento e usos rituais ou construtivos.",year:-8000,era:"Neolítico",prereq:["fogo"],historical:"A cerâmica surgiu em múltiplos contextos; sua cronologia regional varia.",unlock:"Armazenamento e construção aprimorados."},
{id:"botanica",name:"Conhecimento botânico",desc:"Conhecimento empírico de plantas, sementes, fibras, alimentos e usos medicinais.",year:-10000,era:"Conhecimentos ancestrais",prereq:[],unlock:"Bônus de agricultura, saúde e recursos."},
{id:"manejo_florestal",name:"Manejo florestal",desc:"Uso planejado de florestas, fibras e ciclos de regeneração, sem pressupor agricultura intensiva.",year:-8000,era:"Conhecimentos ancestrais",prereq:["ferramentas_pedra"],unlock:"Produção sustentável de madeira."},
{id:"navegacao",name:"Navegação",desc:"Orientação por costa, ventos, correntes, astros e conhecimento ambiental.",year:-7000,era:"Neolítico",prereq:["canoas","astronomia"],unlock:"Rotas marítimas e base da engenharia naval."},
{id:"escrita",name:"Escrita e registros",desc:"Sistemas gráficos para memória, contabilidade, administração e comunicação.",year:-3200,era:"Primeiros Estados",prereq:["agricultura","sedentarismo"],unlock:"Educação, arquivos e administração."},
{id:"administracao",name:"Administração",desc:"Censos, tributação, armazenamento e coordenação territorial.",year:-2500,era:"Primeiros Estados",prereq:["escrita","sedentarismo"],unlock:"Reformas estatais avançadas."},
{id:"metalurgia",name:"Metalurgia",desc:"Tradições de extração, fundição, ligas e trabalho de metais.",year:-1200,era:"Metalurgia avançada",prereq:["metalurgia_cobre","bronze","ferro"],unlock:"Ferramentas, ligas e engenharia de máquinas."},
{id:"engenharia_hidraulica",name:"Engenharia hidráulica",desc:"Canais, diques, reservatórios, terraços e controle de águas.",year:-5000,era:"Neolítico",prereq:["agricultura","irrigacao"],unlock:"Infraestrutura hídrica e agricultura de várzea."},
{id:"matematica",name:"Matemática aplicada",desc:"Contagem, aritmética, geometria e medição para comércio, calendários e engenharia.",year:-3000,era:"Conhecimento antigo",prereq:["escrita"],unlock:"Eficiência em engenharia, comércio e ciência."},
{id:"astronomia",name:"Astronomia",desc:"Observação sistemática dos céus, calendários e orientação.",year:-2500,era:"Conhecimento antigo",prereq:["matematica"],unlock:"Melhor navegação e calendários."},
{id:"cartografia",name:"Cartografia",desc:"Representação sistemática de costas, rotas e territórios.",year:1300,era:"Conhecimento",prereq:["navegacao","matematica"],unlock:"Exploração, comércio e inteligência geográfica."},
{id:"mecanica",name:"Mecânica",desc:"Máquinas, alavancas, engrenagens e movimento.",year:1350,era:"Pré-industrial",prereq:["metalurgia","matematica"],unlock:"Máquinas complexas e base de motores."},
{id:"optica",name:"Óptica",desc:"Luz, lentes e instrumentos de observação.",year:1400,era:"Pré-industrial",prereq:["matematica"],unlock:"Instrumentos científicos e microscopia."},
{id:"quimica",name:"Química",desc:"Substâncias, reações e processos controlados.",year:1450,era:"Ciência experimental",prereq:["metalurgia","mecanica"],unlock:"Materiais avançados e química industrial."},
{id:"medicina",name:"Medicina científica",desc:"Observação clínica, anatomia, farmacologia e prevenção.",year:1450,era:"Ciência experimental",prereq:["botanica","escrita"],unlock:"Medicina institucional e maior saúde."},
{id:"engenharia",name:"Engenharia",desc:"Aplicação sistemática de matemática e materiais à construção.",year:1450,era:"Ciência experimental",prereq:["mecanica","matematica","metalurgia"],unlock:"Infraestrutura complexa e máquinas industriais."},
{id:"fisica",name:"Física experimental",desc:"Medição de forças, movimento, calor, luz e fenômenos.",year:1500,era:"Revolução científica",prereq:["matematica","optica","mecanica"],unlock:"Base para eletricidade e termodinâmica."},
{id:"materiais",name:"Ciência dos materiais",desc:"Pesquisa de metais, ligas, vidro, isolantes e condutores.",year:1500,era:"Revolução científica",prereq:["quimica","metalurgia","fisica"],unlock:"Componentes elétricos, motores e estruturas avançadas."},
{id:"microscopia",name:"Microscopia",desc:"Instrumentos ópticos para observar estruturas microscópicas.",year:1520,era:"Ciência moderna",prereq:["optica","medicina"],unlock:"Microbiologia e medicina avançada."},
{id:"termodinamica",name:"Termodinâmica",desc:"Relação entre calor, trabalho, energia e rendimento.",year:1530,era:"Máquinas",prereq:["fisica","mecanica"],unlock:"Máquinas térmicas e motores a vapor."},
{id:"microbiologia",name:"Microbiologia",desc:"Estudo de microrganismos e agentes de doença.",year:1540,era:"Ciência moderna",prereq:["microscopia","medicina"],unlock:"Saneamento científico e epidemiologia."},
{id:"engenharia_naval",name:"Engenharia naval",desc:"Projeto estrutural de navios, estaleiros e propulsão.",year:1450,era:"Marítima",prereq:["navegacao","mecanica","materiais"],unlock:"Construção de navios avançados."},
{id:"artilharia",name:"Artilharia",desc:"Pólvora, balística e construção de peças metálicas.",year:1400,era:"Militar",prereq:["metalurgia","matematica"],unlock:"Maior poder militar e defesa."},
{id:"vapor",name:"Máquina a vapor",desc:"Conversão de calor em trabalho mecânico.",year:1550,era:"Máquinas",prereq:["termodinamica","materiais","engenharia"],unlock:"Indústria mecanizada, locomotivas e navios a vapor."},
{id:"industria",name:"Indústria mecanizada",desc:"Produção concentrada, padronização e máquinas.",year:1550,era:"Industrial",prereq:["vapor","engenharia","materiais"],unlock:"Grande aumento de produção e urbanização."},
{id:"eletricidade",name:"Eletricidade",desc:"Geração, condução e medição de fenômenos elétricos.",year:1570,era:"Elétrica",prereq:["fisica","materiais","quimica"],unlock:"Geradores, iluminação, redes e motores elétricos."},
{id:"eletromagnetismo",name:"Eletromagnetismo",desc:"Relação entre eletricidade e magnetismo.",year:1580,era:"Elétrica",prereq:["eletricidade","fisica"],unlock:"Motores, geradores e telecomunicações."},
{id:"motor_eletrico",name:"Motor elétrico",desc:"Conversão de energia elétrica em movimento.",year:1590,era:"Elétrica",prereq:["eletromagnetismo","materiais","mecanica"],unlock:"Máquinas elétricas e fábricas modernas."},
{id:"combustao",name:"Motor de combustão",desc:"Conversão de energia química em trabalho mecânico.",year:1600,era:"Motores",prereq:["quimica","materiais","termodinamica"],unlock:"Veículos e aeronaves motorizadas."},
{id:"automacao",name:"Automação",desc:"Máquinas executando sequências com pouca intervenção.",year:1600,era:"Automação",prereq:["motor_eletrico","engenharia"],unlock:"Linhas automatizadas e controle industrial."},
{id:"controle",name:"Teoria de controle",desc:"Sensores, realimentação e controle automático.",year:1620,era:"Sistemas",prereq:["automacao","eletricidade","matematica"],unlock:"Sistemas automáticos e navegação avançada."},
{id:"submersiveis",name:"Submersíveis",desc:"Estruturas e sistemas para operar abaixo da superfície.",year:1580,era:"Marítima",prereq:["engenharia_naval","materiais","eletricidade"],unlock:"Submarinos experimentais."},
{id:"aeronautica",name:"Aeronáutica",desc:"Projeto de veículos mais pesados que o ar.",year:1610,era:"Aeronáutica",prereq:["mecanica","engenharia","combustao"],unlock:"Construção de aeronaves."},
{id:"aerodinamica",name:"Aerodinâmica",desc:"Sustentação, resistência e escoamento do ar.",year:1620,era:"Aeronáutica",prereq:["aeronautica","fisica","matematica"],unlock:"Aeronaves mais eficientes."},
{id:"navegacao_aerea",name:"Navegação aérea",desc:"Instrumentos e orientação de posição em voo.",year:1630,era:"Aeronáutica",prereq:["aerodinamica","cartografia"],unlock:"Maior alcance e segurança."},
{id:"computacao",name:"Computação",desc:"Máquinas para cálculo e processamento automático.",year:1620,era:"Informação",prereq:["matematica","eletricidade","automacao"],unlock:"Computadores eletromecânicos."},
{id:"programacao",name:"Programação",desc:"Lógica formal para instruir máquinas.",year:1640,era:"Informação",prereq:["computacao","matematica"],unlock:"Software e automação programável."},
{id:"semfio",name:"Comunicação sem fio",desc:"Transmissão de sinais por ondas eletromagnéticas.",year:1645,era:"Informação",prereq:["eletromagnetismo","eletricidade"],unlock:"Rádio e comunicação estratégica."},
{id:"dados",name:"Processamento de dados",desc:"Registro, classificação e processamento de informação.",year:1650,era:"Informação",prereq:["computacao","programacao"],unlock:"Administração e inteligência em escala."},
{id:"sistemas",name:"Engenharia de sistemas",desc:"Integração de hardware, software, controle e organização.",year:1660,era:"Sistemas",prereq:["controle","computacao","engenharia"],unlock:"Grandes sistemas tecnológicos integrados."}
];
const milestones=[[1500,"Primeira fase industrial","Metalurgia, escrita e administração ganham escala."],[1530,"Era das máquinas térmicas","Engenharia e energia começam a transformar a economia."],[1560,"Sociedade mecanizada","Indústria, eletricidade e transportes entram em expansão."],[1590,"Era da automação","Precisão, controle e informação tornam-se estratégicos."],[1620,"Era da Aeronáutica","Sistemas de voo, cálculo e engenharia integrada avançam."],[1650,"Era da Informação Sem Fio","Comunicação e processamento de dados reorganizam o Estado."],[1665,"Era dos Sistemas","Engenharia de sistemas conecta indústria, ciência e poder nacional."]];

function era(){if(S.year<1500)return"Era da Fundação";if(S.year<1530)return"Era Industrial Inicial";if(S.year<1560)return"Era das Máquinas Térmicas";if(S.year<1590)return"Era Elétrica";if(S.year<1620)return"Era da Automação";if(S.year<1650)return"Era da Aeronáutica";if(S.year<1665)return"Era da Informação";return"Era dos Sistemas"}
function targetId(kind="strategy"){const map={strategy:"attackTarget",diplomacy:"diplomacyTarget",spy:"spyTarget"};return $(map[kind])?.value || Object.keys(S.nations)[0]}
function setupPreview(){const l=START_CONTEXTS[$("startLocation").value],y=$("startYear").value,pid=$("startPeople").value,p=PEOPLE_PROFILES[pid]||PEOPLE_PROFILES.custom;$("startPreview").innerHTML=`<b>${l[0]}</b> • ${p.name} • ${y}<br>${l[1]}<br><small>${p.culture}. A campanha começa com <b>5 AP</b> e contexto ajustado à região, povo e época.</small>`}
["startLocation","startPeople","startYear"].forEach(id=>$(id).addEventListener("change",setupPreview));setupPreview();
function startCampaign(){
 const y=+$('startYear').value,loc=$('startLocation').value,peopleId=$('startPeople').value,people=PEOPLE_PROFILES[peopleId]||PEOPLE_PROFILES.custom;
 S=structuredClone(initial);S.year=y;S.round=1;S.startLocation=loc;S.startPeople=people.name;S.startRegionName=START_CONTEXTS[loc][0];S.startPeopleId=peopleId;S.actionsLeft=5;S.selectedActions=[];S.selectedRegion=({upaon:"upaon",brasil:"brasil",amazonia:"brasil",nordeste:"brasil",caribe:"caribe",iberia:"iberia",africa:"africa",india:"india",china:"asia"}[loc]||"upaon");S.mapMode="world";S.diplomacyPower=18;S.identity=peopleId;S.mapZoom=1;S.mapHistory=[];Object.entries(people.techStart||{}).forEach(([k,v])=>S.tech[k]=v);S.researchPoints=Object.keys(people.techStart||{}).length;
 S.history=[{year:y,text:`Campanha iniciada em ${START_CONTEXTS[loc][0]} como ${people.name}.`}];
 const scale=Math.max(0,(y-1460)/10);
 S.population*=Math.pow(1.006,scale)*people.pop;S.food*=people.food;S.wood*=people.wood;
 S.resourcePotential={food:1.05,wood:1.05,iron:1,energy:1};
 if(loc==="amazonia")S.resourcePotential={food:1.15,wood:1.45,iron:.9,energy:.95};
 if(loc==="nordeste")S.resourcePotential={food:1.18,wood:.9,iron:1.05,energy:1.1};
 if(loc==="caribe")S.resourcePotential={food:1.1,wood:1.05,iron:.85,energy:1.05};
 if(loc==="iberia")S.resourcePotential={food:1,wood:.85,iron:1.15,energy:1.05};
 if(loc==="africa")S.resourcePotential={food:1.15,wood:1.05,iron:1.2,energy:1.15};
 if(loc==="india")S.resourcePotential={food:1.3,wood:.95,iron:1.1,energy:1.05};
 if(loc==="china")S.resourcePotential={food:1.3,wood:.9,iron:1.25,energy:1.1};
 S.economy=clamp(S.economy+scale*.5+people.industry);S.science=clamp(S.science+scale*.7+people.science);S.industry=clamp(S.industry+scale*.65+people.industry);S.technology=clamp(S.technology+scale*.8+people.science*.4);S.infrastructure=clamp(S.infrastructure+scale*.55);S.education=clamp(S.education+scale*.5+people.education);S.health=clamp(S.health+scale*.45);S.military=clamp(S.military+scale*.45+people.military);S.urban=clamp(S.urban+scale*.3+people.urban,0,96);
 if(loc==="china")S.population*=1.25;if(loc==="india")S.population*=1.1;if(["brasil","amazonia","nordeste"].includes(loc)){S.population*=1.35;S.wood*=1.25;S.food*=1.2}if(loc==="iberia"){S.military+=5;S.economy+=8}
 clampAll();$('startScreen').classList.add('hidden');render();toast(`Campanha iniciada em ${y} como ${people.name}.`)
}
$("startGame").onclick=startCampaign;

function renderIdentity(){
 const p=PEOPLE_PROFILES[S.startPeopleId]||PEOPLE_PROFILES.custom;
 const palettes={upaonense:['🌴','UPAONENSE'],tupinamba:['🪶','TUPINAMBÁ'],guarani:['🌿','GUARANI'],marajoara:['🏺','MARAJOARA'],macroje:['🪶','MACRO-JÊ'],guaicuru:['🐎','GUAICURU'],africano:['🦁','ATLÂNTICO AFRICANO'],sahel:['🐪','SAHEL'],swahili:['⛵','SUAÍLI'],iberico:['⚜️','IBÉRICO'],franca:['⚜️','FRANCO'],inglesa:['⚓','INGLÊS'],holandesa:['🧭','NEERLANDÊS'],norteamericano:['🦅','AMÉRICA DO NORTE'],asteca:['☀️','MEXICA'],maia:['🌞','MAIA'],inca:['⛰️','ANDINO'],caribenho:['🌴','CARIBENHO'],indico:['☀️','ÍNDICO'],sinico:['🐉','SÍNICO'],japonesa:['⛩️','JAPONÊS'],persa:['🦁','PERSA'],polinesia:['🌊','POLINÉSIO'],melanesia:['🌺','MELANÉSIO'],australiano:['🔥','AUSTRALIANO'],custom:['✦','PERSONALIZADO']};
 const [seal,label]=palettes[S.startPeopleId]||palettes.custom;
 $("identitySeal").textContent=seal; $("identityName").textContent=p.name; $("identityMotto").textContent=p.culture+'.';
 $("identityTags").innerHTML=p.traits.slice(0,3).map(t=>`<span>${t}</span>`).join('');
 $("logoMark").textContent=seal;
 const bar=$("identityBar"); if(bar)bar.dataset.people=S.startPeopleId||'custom';
 const startEmblem=$("startScreen")?.querySelector('.start-emblem'); if(startEmblem)startEmblem.textContent=seal;
}

function render(){
 renderIdentity();
 $("year").textContent=S.year;$("round").textContent=S.round;$("eraName").textContent=era();$("actionCount").textContent=`${S.actionsLeft} AP restantes`;
 $("headline").textContent=S.year<1500?"O nascimento de uma civilização":S.year<1600?"Uma potência em transformação":"Uma civilização tecnológica em ascensão";
 $("statusText").textContent=`${fmt(S.population)} habitantes • ${Math.round(S.urban)}% urbanos • ${S.warsWon} guerras vencidas • ${S.alliances.length} alianças`;
 $("actionDots").innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<S.actionsLeft?"on":""}"></i>`).join("");
 $("metrics").innerHTML=[['👥','População',fmt(S.population)],['🏙️','Urbanização',Math.round(S.urban)+'%'],['💰','Tesouro',money(S.treasury)],['🌾','Alimento',fmt(S.food)],['⚙️','Indústria',Math.round(S.industry)],['🔬','Ciência',Math.round(S.science)],['🧠','Tecnologia',Math.round(S.technology)],['⚔️','Militar',Math.round(S.military)],['🕊️','Diplomacia',Math.round(S.diplomacyPower)],['🛡️','Prontidão',Math.round(S.readiness)]].map(x=>`<div class="metric"><span>${x[0]}</span><small>${x[1]}</small><b>${x[2]}</b></div>`).join('');
 renderActions();renderTech();renderInstitutions();renderEconomy();renderMap();renderSociety();renderMilitary();renderDiplomacy();renderTimeline();populateTargets();
 $("latestEvent").textContent=S.history.at(-1)?.text||"Nenhum evento registrado.";
}
function techYearLabel(y){const n=Number(y)||0;return n<0?`${Math.abs(n).toLocaleString("pt-BR")} a.C.`:`${n} d.C.`}
function techHas(id){return Number(S.tech?.[id]||0)>=1}
function techById(id){return tech.find(t=>t.id===id)}
function techAvailable(t){return S.year>=t.year && (t.prereq||[]).every(p=>techHas(p))}
function techBlockReason(t){if(S.year<t.year)return `Ano mínimo: ${techYearLabel(t.year)}`;const missing=(t.prereq||[]).filter(p=>!techHas(p)).map(p=>techById(p)?.name||p);return missing.length?`Requer: ${missing.join(', ')}`:`Pronta para pesquisa`}
function renderActions(){
 $("actionGrid").innerHTML=actions.map(a=>{const ap=a.ap||1;const techOk=!a.techReq||a.techReq.every(techHas);const disabled=S.actionsLeft<ap||!techOk;const reason=!techOk?`Requer: ${a.techReq.filter(x=>!techHas(x)).map(x=>techById(x)?.name||x).join(', ')}`:'';return `<button class="action" data-action="${a.id}" ${disabled?'disabled':''}><span class="icon">${a.icon}</span><span class="cat">${a.cat} • ${ap} AP</span><h3>${a.name}</h3><p>${a.desc}</p><span class="cost">${a.cost}</span>${reason?`<small class="lock-note">🔒 ${reason}</small>`:''}</button>`}).join('');
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>executeAction(b.dataset.action));
}
function executeAction(id){const a=actions.find(x=>x.id===id);if(!a)return;const ap=a.ap||1;const requirements={industry:[['iron',4,'Ferro insuficiente.'],['treasury',15,'Tesouro insuficiente.']],energy:[['wood',6,'Madeira insuficiente.'],['treasury',10,'Tesouro insuficiente.']],transport:[['wood',8,'Madeira insuficiente.'],['treasury',12,'Tesouro insuficiente.']],naval:[['wood',10,'Madeira insuficiente.'],['iron',3,'Ferro insuficiente.']],compute:[['treasury',15,'Tesouro insuficiente.']],mil:[['food',4,'Alimento insuficiente.'],['treasury',12,'Tesouro insuficiente.']],fort:[['iron',3,'Ferro insuficiente.'],['treasury',10,'Tesouro insuficiente.']],admin:[['treasury',8,'Tesouro insuficiente.']],edu:[['treasury',10,'Tesouro insuficiente.']],science:[['treasury',12,'Tesouro insuficiente.']],health:[['treasury',10,'Tesouro insuficiente.']],trade:[['treasury',3,'Tesouro insuficiente.']],resources:[['treasury',7,'Tesouro insuficiente.']],urban:[['treasury',9,'Tesouro insuficiente.']],influence:[['treasury',6,'Tesouro insuficiente.']],intelligence:[['treasury',8,'Tesouro insuficiente.']]};if(S.actionsLeft<ap)return toast('Pontos de ação insuficientes.');for(const [key,value,msg] of (requirements[id]||[])){if((S[key]||0)<value)return toast(msg)}S.actionsLeft-=ap;a.apply();S.selectedActions.push(a.name);S.history.push({year:S.year,text:`${a.name}.`});clampAll();render();toast(`${a.name} executada.`)}
function techCost(t){return (t.prereq||[]).length>=3?2:1}
function techAvailable(t){return S.year>=t.year && (t.prereq||[]).every(p=>techHas(p))}
function techBlockReason(t){if(S.year<t.year)return `Ano mínimo: ${t.year}`;const missing=(t.prereq||[]).filter(p=>!techHas(p)).map(p=>techById(p)?.name||p);return missing.length?`Requer: ${missing.join(', ')}`:`Pronta para pesquisa`}
function researchTechnology(id){const t=techById(id);if(!t)return;if(techHas(id))return toast('Tecnologia já pesquisada.');if(!techAvailable(t))return toast(techBlockReason(t));const cost=techCost(t);if(S.actionsLeft<1)return toast('Sem AP para pesquisa.');if(S.researchPoints<cost)return toast(`Pontos de pesquisa insuficientes: ${cost} necessários.`);S.actionsLeft--;S.researchPoints-=cost;const p=PEOPLE_PROFILES[S.startPeopleId]||PEOPLE_PROFILES.custom;const bonus=p.techBonus?.[id]||0;S.tech[id]=1;S.science+=2+bonus*3;S.technology+=1.5+bonus;S.history.push({year:S.year,text:`Pesquisa concluída: ${t.name}. ${t.unlock}`});clampAll();render();toast(`Tecnologia desbloqueada: ${t.name}.`)}
function renderTech(){
 const p=PEOPLE_PROFILES[S.startPeopleId]||PEOPLE_PROFILES.custom;
 const researched=tech.filter(t=>techHas(t.id)).length;
 $("researchLedger").innerHTML=`<div class="research-card"><span>🔬 PONTOS DE PESQUISA</span><b>${S.researchPoints.toFixed(1)}</b><small>Ganhos com ciência, educação e institutos. Pesquisas custam 1–2 AP + pontos.</small></div><div class="research-card"><span>📚 PROGRESSO</span><b>${researched}/${tech.length}</b><small>${p.name} recebe bônus próprios em áreas coerentes com sua tradição.</small></div><div class="research-card"><span>⚙️ PROJETOS DESBLOQUEADOS</span><b>${Object.values(S.projects).reduce((a,b)=>a+b,0)}</b><small>Navios, geradores, aeronaves e computadores dependem da cadeia tecnológica.</small></div>`;
 const eras=[...new Set(tech.map(t=>t.era))];
 $("techTree").innerHTML=eras.map(eraName=>{const nodes=tech.filter(t=>t.era===eraName);return `<div class="tech-era"><div class="tech-era-head"><span>${eraName}</span><small>${nodes.filter(t=>techHas(t.id)).length}/${nodes.length} dominadas</small></div><div class="tech-lane">${nodes.map(t=>{const level=Number(S.tech?.[t.id]||0),done=level>=1,available=techAvailable(t),cost=techCost(t),req=(t.prereq||[]).map(x=>techById(x)?.name||x);return `<article class="tech ${done?'done':''} ${available&&!done?'available':''} ${!available&&!done?'locked':''}"><div class="tech-icon">${done?'✓':available?'◆':'◇'}</div><h3>${t.name}</h3><p>${t.desc}</p><div class="tech-chain"><span>${techYearLabel(t.year)}</span><b>→</b><span>${req.length?req.join(' + '):'fundamento'}</span></div><div class="bar"><i style="width:${done?100:available?34:8}%"></i></div><small>${done?'Pesquisada':techBlockReason(t)}</small><div class="unlock"><b>Desbloqueia:</b> ${t.unlock}</div>${t.historical?`<div class="tech-history">📜 ${t.historical}</div>`:''}${!done&&available?`<button class="research-btn" data-research="${t.id}">🔬 Pesquisar • ${cost} RP + 1 AP</button>`:''}</article>`}).join('')}</div></div>`}).join('');
 document.querySelectorAll('[data-research]').forEach(b=>b.onclick=()=>researchTechnology(b.dataset.research));
}

const INSTITUTIONS=[
{id:'council',name:'Conselho de Estado',icon:'⚖️',desc:'Coordenação política e administração regular.',req:[],year:1000,cost:8,effects:'Estabilidade +4 • Infraestrutura +2'},
{id:'academy',name:'Academia de Ciências',icon:'🔬',desc:'Institucionaliza pesquisa, observação e formação de especialistas.',req:['escrita','matematica'],year:1200,cost:14,effects:'Ciência +5 • Educação +2 • +RP'},
{id:'guilds',name:'Corporações de Ofício',icon:'🛠️',desc:'Organiza artesãos, padrões e transmissão de técnicas.',req:['metalurgia'],year:1200,cost:10,effects:'Indústria +3 • Máquinas +1'},
{id:'navalOffice',name:'Casa de Navegação',icon:'⚓',desc:'Cartografia, pilotos, portos e construção naval sob coordenação estatal.',req:['navegacao','cartografia'],year:1300,cost:12,effects:'Comércio +5 • Militar +3'},
{id:'bank',name:'Banco Público',icon:'🏦',desc:'Crédito, tesouro e financiamento de infraestrutura e comércio.',req:['administracao','matematica'],year:1400,cost:18,effects:'Economia +5 • Tesouro +15'},
{id:'warCollege',name:'Estado-Maior',icon:'🪖',desc:'Profissionaliza logística, inteligência e planejamento militar.',req:['administracao','artilharia'],year:1450,cost:16,effects:'Militar +4 • Prontidão +6'},
{id:'telegraph',name:'Serviço de Comunicações',icon:'📡',desc:'Integra informação estratégica e administração territorial.',req:['eletromagnetismo','semfio'],year:1645,cost:22,effects:'Diplomacia +5 • Prontidão +4'}
];
function adoptInstitution(id){const i=INSTITUTIONS.find(x=>x.id===id);if(!i)return;if((S.institutions||[]).includes(id))return toast('Instituição já adotada.');if(S.year<i.year)return toast(`Disponível a partir de ${i.year}.`);const miss=i.req.filter(x=>!techHas(x));if(miss.length)return toast(`Requer: ${miss.map(x=>techById(x)?.name||x).join(', ')}`);if(S.actionsLeft<1)return toast('Sem AP.');if(S.treasury<i.cost)return toast('Tesouro insuficiente.');S.actionsLeft--;S.treasury-=i.cost;S.institutions.push(id);if(id==='council'){S.stability+=4;S.infrastructure+=2}if(id==='academy'){S.science+=5;S.education+=2;S.researchPoints+=2}if(id==='guilds'){S.industry+=3;S.machines+=1}if(id==='navalOffice'){S.trade+=5;S.military+=3}if(id==='bank'){S.economy+=5;S.treasury+=15}if(id==='warCollege'){S.military+=4;S.readiness+=6}if(id==='telegraph'){S.diplomacyPower+=5;S.readiness+=4}S.history.push({year:S.year,text:`Instituição fundada: ${i.name}.`});clampAll();render();toast(`${i.name} estabelecida.`)}
function renderInstitutions(){const owned=new Set(S.institutions||[]);$("institutionSummary").textContent=`${owned.size} instituições`;$("institutionGrid").innerHTML=INSTITUTIONS.map(i=>{const has=owned.has(i.id),available=S.year>=i.year&&i.req.every(techHas),missing=i.req.filter(x=>!techHas(x)).map(x=>techById(x)?.name||x);return `<article class="institution ${has?'owned':''} ${!has&&!available?'locked':''}"><div class="institution-icon">${i.icon}</div><div><span class="cat">INSTITUIÇÃO • ${i.year}</span><h3>${i.name}</h3><p>${i.desc}</p><div class="institution-req">${i.req.length?`Requer: ${i.req.map(x=>techById(x)?.name||x).join(' • ')}`:'Fundamento administrativo'}</div><div class="institution-effect">${i.effects}</div>${has?'<b class="owned-label">✓ ESTABELECIDA</b>':`<button class="institution-btn" data-institution="${i.id}" ${!available?'disabled':''}>Estabelecer • ¤ ${i.cost} • 1 AP</button>${missing.length?`<small class="lock-note">🔒 ${missing.join(', ')}</small>`:''}`}</div></article>`}).join('');document.querySelectorAll('[data-institution]').forEach(b=>b.onclick=()=>adoptInstitution(b.dataset.institution))}

function renderEconomy(){ensureEconomyModel();$("resources").innerHTML=[['💰','Tesouro',money(S.treasury),`fluxo ${S.economyModel.lastFlow.treasury>=0?'+':''}${Math.round(S.economyModel.lastFlow.treasury)}/ano`],['🌾','Alimento',fmt(S.food),`fluxo ${S.economyModel.lastFlow.food>=0?'+':''}${S.economyModel.lastFlow.food.toFixed(1)}`],['⛓️','Ferro',fmt(S.iron),`fluxo ${S.economyModel.lastFlow.iron>=0?'+':''}${S.economyModel.lastFlow.iron.toFixed(1)}`],['🪵','Madeira',fmt(S.wood),`fluxo ${S.economyModel.lastFlow.wood>=0?'+':''}${S.economyModel.lastFlow.wood.toFixed(1)}`],['⚙️','Máquinas',fmt(S.machines),`fluxo ${S.economyModel.lastFlow.machines>=0?'+':''}${S.economyModel.lastFlow.machines.toFixed(1)}`],['⚡','Energia',fmt(S.energyStock),`fluxo ${S.economyModel.lastFlow.energy>=0?'+':''}${S.economyModel.lastFlow.energy.toFixed(1)}`]].map(x=>`<div class="resource"><div class="r-icon">${x[0]}</div><div class="r-name">${x[1]}</div><b>${x[2]}</b><small>${x[3]}</small></div>`).join('');$("production").innerHTML=[['Agricultura',S.workforce.agro],['Pesca',S.workforce.pesca],['Mineração',S.workforce.minera],['Manufatura',S.workforce.manufatura],['Indústria mecanizada',S.workforce.industria],['Navegação',S.workforce.navegacao],['Ciência',S.workforce.ciencia],['Serviços',S.workforce.servicos]].map(x=>bar(x[0],x[1],60)).join('');$("economyBars").innerHTML=[['Economia',S.economy],['Comércio',S.trade],['Infraestrutura',S.infrastructure],['Energia',S.energy],['Estabilidade',S.stability]].map(x=>bar(x[0],x[1],100)).join('');const prices=S.economyModel.prices;const status=[S.economyModel.shortages.length?`⚠️ Escassez: ${S.economyModel.shortages.join(', ')}`:'✓ Estoques básicos estáveis',S.economyModel.surplus.length?`📦 Excedente: ${S.economyModel.surplus.join(', ')}`:'',`Preços: alimento ${prices.food.toFixed(2)} • madeira ${prices.wood.toFixed(2)} • ferro ${prices.iron.toFixed(2)} • energia ${prices.energy.toFixed(2)}`].filter(Boolean).join('<br>');const box=document.getElementById('economyFlow');if(box)box.innerHTML=status;}

function bar(n,v,max){return `<div class="bar-row"><div class="bar-head"><span>${n}</span><b>${Math.round(v)}</b></div><div class="bar"><i style="width:${Math.min(100,v/max*100)}%"></i></div></div>`}
function renderMap(){
 const mode=S.mapMode||'world',id=S.selectedRegion||'upaon';
 document.querySelectorAll('.map-node.world').forEach(b=>{b.classList.toggle('selected',b.dataset.region===id);b.setAttribute('aria-pressed',b.dataset.region===id?'true':'false')});
 document.querySelectorAll('.map-mode').forEach(b=>b.classList.toggle('active',b.dataset.mapMode===mode));
 const board=$("mapBoard"); if(board){board.dataset.mode=mode;board.dataset.zoom=S.mapZoom||1;}
 const regionMeta={
  upaon:{title:'🌴 Upaon-Açu',type:'Núcleo nacional',value:fmt(S.population)+' hab.',desc:'Centro político da campanha; a ilha conecta comércio, defesa naval, ciência e urbanização.',tension:Math.round(100-S.stability),influence:Math.round(S.diplomacyPower),routes:Math.max(1,Math.round(S.trade/10)),resource:'Madeira • pesca • porto'},
  brasil:{title:'🌎 Brasil',type:'Espaço continental',value:Math.round(S.nations.brasil?.territory||35)+' u.',desc:'Profundidade territorial e recursos; a relação com os Estados do Brasil afeta o entorno continental.',tension:Math.round(S.nations.brasil?.tension||0),influence:Math.round(S.influence.brasil||0),routes:Math.round((S.relations.brasil?.trade||0)/10),resource:'Madeira • alimentos • minerais'},
  caribe:{title:'🏝️ Caribe',type:'Teatro insular',value:Math.round(S.nations.caribe?.territory||5)+' u.',desc:'Arquipélagos, portos e gargalos marítimos; excelente para comércio, inteligência e projeção naval.',tension:Math.round(S.nations.caribe?.tension||0),influence:Math.round(S.influence.caribe||0),routes:Math.round((S.relations.caribe?.trade||0)/8),resource:'Portos • comércio • pesca'},
  iberia:{title:'⚓ Ibéria',type:'Centro europeu',value:Math.round((S.nations.portugal?.territory||9)+(S.nations.espanha?.territory||10))+' u.',desc:'Portugal e Espanha concentram navegação, rivalidade e acesso ao Atlântico oriental.',tension:Math.round(((S.nations.portugal?.tension||0)+(S.nations.espanha?.tension||0))/2),influence:Math.round((S.influence.portugal||0)+(S.influence.espanha||0)),routes:Math.round(((S.relations.portugal?.trade||0)+(S.relations.espanha?.trade||0))/10),resource:'Portos • navegação • manufatura'},
  europa:{title:'♜ Europa',type:'Potências europeias',value:Math.round(Object.values(S.nations).filter(n=>n.region==='Europa').reduce((a,n)=>a+n.territory,0))+' u.',desc:'Grande centro de competição militar, científica, comercial e diplomática.',tension:Math.round(Object.values(S.nations).filter(n=>n.region==='Europa').reduce((a,n)=>a+n.tension,0)/5),influence:Math.round(Object.keys(S.nations).filter(k=>S.nations[k].region==='Europa').reduce((a,k)=>a+(S.influence[k]||0),0)),routes:Math.round(Object.keys(S.relations).filter(k=>S.nations[k]?.region==='Europa').reduce((a,k)=>a+(S.relations[k]?.trade||0),0)/15),resource:'Ciência • comércio • indústria'},
  africa:{title:'🌍 África Ocidental',type:'Teatro atlântico',value:Math.round(S.nations.magrebe?.territory||12)+' u.',desc:'Costa atlântica, rotas africanas e conexão com o interior; importante para comércio e diplomacia.',tension:Math.round(S.nations.magrebe?.tension||0),influence:Math.round(S.influence.magrebe||0),routes:Math.round((S.relations.magrebe?.trade||0)/8),resource:'Ouro • madeira • alimentos'},
  magrebe:{title:'☪ Magrebe',type:'Ponte mediterrânea',value:Math.round(S.nations.magrebe?.territory||12)+' u.',desc:'Ponto de contato entre Mediterrâneo, África e rotas oceânicas.',tension:Math.round(S.nations.magrebe?.tension||0),influence:Math.round(S.influence.magrebe||0),routes:Math.round((S.relations.magrebe?.trade||0)/8),resource:'Comércio • cavalaria • portos'},
  india:{title:'◈ Índia',type:'Potência do Índico',value:Math.round(S.nations.india?.territory||30)+' u.',desc:'Grande espaço comercial e científico, conectado por rotas oceânicas.',tension:Math.round(S.nations.india?.tension||0),influence:Math.round(S.influence.india||0),routes:Math.round((S.relations.india?.trade||0)/8),resource:'Especiarias • tecidos • conhecimento'},
  asia:{title:'🏯 China e Ásia',type:'Centro oriental',value:Math.round((S.nations.china?.territory||45)+(S.nations.india?.territory||30))+' u.',desc:'Grandes centros populacionais e produtivos; distância aumenta o custo diplomático.',tension:Math.round(((S.nations.china?.tension||0)+(S.nations.india?.tension||0))/2),influence:Math.round((S.influence.china||0)+(S.influence.india||0)),routes:Math.round(((S.relations.china?.trade||0)+(S.relations.india?.trade||0))/8),resource:'Seda • metais • ciência'},
  america_norte:{title:'🦅 América do Norte',type:'Teatro continental',value:'diverso',desc:'Confederações, sociedades agrícolas e futuras potências disputam recursos e rotas do norte.',tension:12,influence:Math.round(S.influence.america_norte||0),routes:2,resource:'Madeira • peles • agricultura'},
  mesoamerica:{title:'☀️ Mesoamérica',type:'Cidades e Estados',value:'centros urbanos',desc:'Espaço de alta densidade urbana e tradições matemáticas, agrícolas e astronômicas.',tension:16,influence:Math.round(S.influence.mesoamerica||0),routes:2,resource:'Milho • obsidiana • conhecimento'},
  andes:{title:'⛰️ Andes',type:'Espaço de altitude',value:'territórios andinos',desc:'Montanhas, estradas e agricultura de altitude criam uma geografia estratégica singular.',tension:10,influence:Math.round(S.influence.andes||0),routes:1,resource:'Metais • terraços • fibras'},
  oceania:{title:'🌊 Oceania',type:'Teatro insular',value:'arquipélagos',desc:'Longas distâncias, navegação oceânica e redes insulares condicionam o poder regional.',tension:8,influence:Math.round(S.influence.oceania||0),routes:2,resource:'Pesca • madeira • navegação'}
 };
 const data=regionMeta[id]||regionMeta.upaon;
 const modeText={world:'Visão global — selecione um centro para inspecionar sua posição estratégica.',atlantic:'Teatro Atlântico — destaque para comércio, portos, rotas e projeção marítima.',political:'Camada política — influência, tensão e centros de poder ficam em primeiro plano.',routes:'Camada de rotas — linhas comerciais e navais ganham contraste.',resources:'Camada de recursos — símbolos indicam os recursos estratégicos associados a cada região.'}[mode];
 const activeRoutes=Object.entries(S.relations).filter(([k,r])=>r.trade>=25).map(([k])=>k);
 const resourceIcons={upaon:'🌴 🐟 ⚓',brasil:'🌳 🌾 ⛏️',caribe:'⚓ 🐟 💰',iberia:'⚓ ⛵ ⚙️',europa:'🔬 ⚙️ 💰',africa:'💰 🌳 🌾',magrebe:'🐎 ⚓ 💰',india:'🧵 🌶️ 🔬',asia:'🧵 ⛏️ 🔬',america_norte:'🌲 🦌 🌾',mesoamerica:'🌽 🪨 🔭',andes:'⛏️ 🌾 🧶',oceania:'🐟 🌴 🛶'};
 const direct=['brasil','caribe','iberia','europa','africa','magrebe','india','asia'].includes(id);const actionsForMap=id==='upaon'?`<button class="map-action" data-map-action="develop">🏗️ Desenvolver região <small>1 AP</small></button>`:direct?`<button class="map-action" data-map-action="influence">🕸️ Investir influência <small>1 AP</small></button><button class="map-action" data-map-action="route">🚢 Explorar rota <small>1 AP</small></button>`:`<button class="map-action" data-map-action="survey">🧭 Reconhecer região <small>1 AP</small></button>`;
 $("regionInfo").innerHTML=`<div class="map-info-head"><span class="eyebrow">${mode.toUpperCase()}</span><h3>${data.title}</h3><div class="big">${data.value}</div><p class="desc">${data.desc}</p></div><div class="region-seal">${resourceIcons[id]||'✦'}</div><div class="map-mode-note">${modeText}</div><div class="map-facts"><div><span>Influência</span><b>${data.influence}</b></div><div><span>Tensão</span><b>${data.tension}</b></div><div><span>Rotas</span><b>${Math.max(0,data.routes)}</b></div><div><span>Recursos</span><b>${data.resource}</b></div></div><div class="map-actions"><b>INTERAÇÃO</b>${actionsForMap}</div><div class="hint">Rotas comerciais ativas: <b>${activeRoutes.length}</b>. Estas ações alteram o estado e ficam registradas na história.</div>`;
 document.querySelectorAll('[data-map-action]').forEach(b=>b.onclick=()=>mapAction(b.dataset.mapAction,id));
}
function mapAction(type,id){
 if(S.actionsLeft<1)return toast('Sem AP.');
 if(id==='upaon'&&type==='develop'){S.actionsLeft--;S.infrastructure+=4;S.urban+=1.5;S.economy+=2;S.treasury=Math.max(0,S.treasury-6);S.history.push({year:S.year,text:'Desenvolvimento regional em Upaon-Açu: infraestrutura e urbanização ampliadas.'});toast('Região desenvolvida.');}
 else if(type==='influence'){if(!S.nations[id]&&id!=='iberia'&&id!=='europa')return toast('Região sem alvo diplomático direto.');S.actionsLeft--;const target=id==='iberia'?'portugal':id==='europa'?'franca':id==='africa'?'magrebe':id==='asia'?'china':id;S.influence[target]=(S.influence[target]||0)+8; if(S.relations[target])S.relations[target].trust=clamp(S.relations[target].trust+4);S.diplomacyPower+=2;S.treasury=Math.max(0,S.treasury-5);S.history.push({year:S.year,text:`Presença estratégica ampliada em ${regionLabel(id)}.`});toast('Influência ampliada.');}
 else if(type==='route'){if(!S.relations[id]&&id!=='iberia'&&id!=='europa')return toast('Não há rota diplomática direta para esta região.');S.actionsLeft--;const target=id==='iberia'?'portugal':id==='europa'?'holanda':id==='africa'?'magrebe':id==='asia'?'india':id; if(S.relations[target])S.relations[target].trade=clamp(S.relations[target].trade+8);S.trade+=6;S.economy+=2;S.treasury+=7;S.influence[target]=(S.influence[target]||0)+3;S.history.push({year:S.year,text:`Expedição comercial abriu uma nova rota para ${regionLabel(id)}.`});toast('Rota explorada.');}
 else if(type==='survey'){S.actionsLeft--;S.influence[id]=(S.influence[id]||0)+4;S.science+=1;S.technology+=.5;S.history.push({year:S.year,text:`Expedição de reconhecimento em ${regionLabel(id)}: geografia e recursos registrados.`});toast(`Reconhecimento concluído em ${regionLabel(id)}.`);}
 clampAll();render();
}
function regionLabel(id){return {upaon:'Upaon-Açu',brasil:'Brasil',caribe:'Caribe',iberia:'Ibéria',europa:'Europa',africa:'África Ocidental',magrebe:'Magrebe',india:'Índia',asia:'Ásia',america_norte:'América do Norte',mesoamerica:'Mesoamérica',andes:'Andes',oceania:'Oceania'}[id]||id;}
function regionTension(r){const map={iberia:['portugal','espanha'],europa:['portugal','espanha','franca','holanda','inglaterra'],africa:['magrebe'],magrebe:['magrebe'],asia:['china','india'],india:['india'],brasil:['brasil'],caribe:['caribe']};const ids=map[r]||[];const ns=ids.map(id=>S.nations[id]).filter(Boolean);return ns.length?ns.reduce((a,n)=>a+n.tension,0)/ns.length:0}
function renderSociety(){const city=S.cities.saoLuis;$("demography").innerHTML=[['População',fmt(S.population)],['Urbanização',Math.round(S.urban)+'%'],['Saúde',Math.round(S.health)],['Educação',Math.round(S.education)],['Estabilidade',Math.round(S.stability)],['São Luís',fmt(city.pop)]].map(x=>`<div class="row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$("workforce").innerHTML=Object.entries(S.workforce).map(([k,v])=>bar(k[0].toUpperCase()+k.slice(1),v,60)).join('');$("censusReport").innerHTML=S.censuses.at(-1)?`Ano ${S.censuses.at(-1).year}: <b>${fmt(S.censuses.at(-1).population)}</b> habitantes, ${S.censuses.at(-1).urban}% urbanos.`:"Nenhum censo.";drawChart()}
function renderMilitary(){$("militaryStats").innerHTML=[['Força militar',S.military],['Prontidão',S.readiness],['Tecnologia',S.technology],['Logística',S.infrastructure],['Guerras vencidas',S.warsWon],['Guerras perdidas',S.warsLost]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${typeof x[1]==='number'?Math.round(x[1]):x[1]}</b></div>`).join('');$("exerciseGrid").innerHTML=[{name:'Exercício terrestre',icon:'🪖',fn:'exerciseLand'},{name:'Exercício naval',icon:'⚓',fn:'exerciseNaval'},{name:'Exercício aéreo',icon:'✈️',fn:'exerciseAir'},{name:'Mobilização logística',icon:'📦',fn:'exerciseLog'}].map(x=>`<button class="action" data-ex="${x.fn}"><span class="icon">${x.icon}</span><span class="cat">1 AP</span><h3>${x.name}</h3><p>Melhora prontidão sem iniciar guerra.</p></button>`).join('');document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>exercise(b.dataset.ex))}
function exercise(type){if(S.actionsLeft<1)return toast('Sem AP.');S.actionsLeft--;S.readiness+=type==='exerciseLog'?6:8;S.military+=type==='exerciseNaval'?1.5:1;S.history.push({year:S.year,text:`${type.replace('exercise','')} realizado; prontidão elevada.`});clampAll();render();toast('Exercício concluído sem iniciar guerra.')}
function populateTargets(){const opts=Object.entries(S.nations).map(([id,n])=>`<option value="${id}">${n.flag} ${n.name}</option>`).join('');['attackTarget','spyTarget','diplomacyTarget'].forEach(id=>{if($(id)){const old=$(id).value;$(id).innerHTML=opts;if(old&&S.nations[old])$(id).value=old;}});}
function strategicAttack(){const id=targetId(),n=S.nations[id],rel=S.relations[id];if(!n)return toast('Alvo inválido.');if(S.actionsLeft<2)return toast('Ataque exige 2 AP.');if(S.alliances.includes(id)||rel?.alliance==='alliance')return toast(`Você possui uma aliança com ${n.name}. Rompa a aliança antes de atacar.`);if(S.warStatus[id]==='war')return toast(`A guerra contra ${n.name} já está em andamento.`);if(S.warStatus[id]==='peace')S.warStatus[id]=null;S.actionsLeft-=2;S.warStatus[id]='war';n.tension=clamp(n.tension+25);const ours=S.military+S.tech.sistemas*2+S.tech.controle*1.5+S.readiness*.25+S.infrastructure*.15;const theirs=n.military+n.stability*.25+Math.random()*22;if(ours>theirs*1.15){n.military=Math.max(0,n.military-8);n.stability-=5;S.military-=2;S.economy-=2;S.diplomacyPower-=6;S.warsWon++;S.territory+=.15;S.warStatus[id]='victory';S.history.push({year:S.year,text:`Guerra contra ${n.name}: vitória estratégica; influência territorial ampliada.`});toast(`Vitória contra ${n.name}.`)}else{n.military=Math.max(0,n.military-3);S.military-=5;S.stability-=7;S.economy-=4;S.diplomacyPower-=8;S.warsLost++;S.warStatus[id]='war';S.history.push({year:S.year,text:`Guerra contra ${n.name}: ofensiva repelida.`});toast(`Ofensiva repelida por ${n.name}.`)}clampAll();render()}
function espionage(){if(S.actionsLeft<1)return toast('Sem AP.');const id=targetId('spy'),n=S.nations[id];if(!n)return toast('Alvo inválido.');S.actionsLeft--;const intel=clamp(S.science*.45+S.tech.dados*4+S.tech.semfio*3+Math.random()*25);if(Math.random()*100<intel){S.science+=2;S.technology+=1;S.influence[id]=(S.influence[id]||0)+4;S.history.push({year:S.year,text:`Inteligência obtida sobre ${n.name}: forças e economia avaliadas.`});toast(`Informações obtidas sobre ${n.name}.`)}else{n.tension=clamp(n.tension+10);n.attitude=clamp(n.attitude-6,-100,100);S.diplomacyPower-=3;S.history.push({year:S.year,text:`Espionagem contra ${n.name} foi detectada.`});toast(`Operação detectada por ${n.name}.`)}clampAll();render()}
function treaty(type){if(S.actionsLeft<1)return toast('Sem AP.');const id=targetId('diplomacy'),n=S.nations[id],d=S.relations[id];if(!n||!d)return toast('Alvo diplomático inválido.');if(type==='peace'&&S.warStatus[id]==='war'){S.actionsLeft--;d.trust=clamp(d.trust+18);n.tension=clamp(n.tension-20);n.attitude=clamp(n.attitude+12,-100,100);S.stability+=2;S.warStatus[id]='peace';S.history.push({year:S.year,text:`Armistício e pacto de não agressão com ${n.name}.`});clampAll();render();return toast(`Paz negociada com ${n.name}.`)}S.actionsLeft--;if(type==='trade'){d.trade=clamp(d.trade+12);n.trade=clamp(n.trade+8);S.economy+=3;S.treasury+=6;n.tension=clamp(n.tension-6)}if(type==='science'){d.science+=8;S.science+=3;S.technology+=2;n.attitude=clamp(n.attitude+5,-100,100)}if(type==='peace'){d.trust=clamp(d.trust+12);n.tension=clamp(n.tension-15);n.attitude=clamp(n.attitude+10,-100,100);S.stability+=2;S.warStatus[id]='peace'}S.history.push({year:S.year,text:`Tratado ${type==='trade'?'comercial':type==='science'?'científico':'de não agressão'} firmado com ${n.name}.`});clampAll();render();toast(`Tratado firmado com ${n.name}.`)}
function alliance(){if(S.actionsLeft<2)return toast('Aliança exige 2 AP.');const id=targetId('diplomacy'),n=S.nations[id],d=S.relations[id];if(!n||!d)return toast('Alvo diplomático inválido.');if(S.warStatus[id]==='war')return toast('Não é possível formar aliança durante uma guerra.');if(S.alliances.includes(id))return toast(`Você já é aliado de ${n.name}.`);if(d.trust<25||n.attitude<15)return toast('Confiança insuficiente para uma aliança.');S.actionsLeft-=2;S.alliances.push(id);d.alliance='alliance';n.alliance='Upaon-Açu';n.tension=clamp(n.tension-12);S.diplomacyPower+=5;S.military+=2;S.history.push({year:S.year,text:`Aliança estratégica formada com ${n.name}.`});clampAll();render();toast(`Aliança formada com ${n.name}.`)}
function tradeRoute(){if(S.actionsLeft<1)return toast('Sem AP.');const id=targetId('diplomacy'),n=S.nations[id],d=S.relations[id];if(!n||!d)return toast('Alvo comercial inválido.');if(S.warStatus[id]==='war')return toast('Não é possível abrir rota comercial durante uma guerra.');if(S.tradeRoutes[id])return toast(`Já existe uma rota comercial com ${n.name}.`);if((d.trade||0)<12)return toast('Comércio insuficiente: firme primeiro um tratado comercial ou aumente a relação.');S.actionsLeft--;S.tradeRoutes[id]={year:S.year,level:1,capacity:14,profit:6,risk:Math.max(8,30-(d.trust||0)/2),product:n.region==='Europa'?'manufaturas e ferramentas':n.region==='Ásia'?'tecidos e conhecimento':n.region==='África'?'ouro e matérias-primas':'alimentos e madeira'};S.trade+=8;S.economy+=2;S.treasury+=10;S.influence[id]=(S.influence[id]||0)+5;n.attitude=clamp(n.attitude+3,-100,100);d.trade=clamp(d.trade+5);S.history.push({year:S.year,text:`Nova rota comercial com ${n.name}.`});clampAll();render();toast(`Rota comercial aberta com ${n.name}.`)}
function doCensus(silent=false){S.censuses.push({year:S.year,population:S.population,urban:Math.round(S.urban),education:Math.round(S.education),health:Math.round(S.health)});if(!silent)toast('Censo registrado.')}
function randomEvent(){const pool=[['🌾 Colheita favorável','A produção de alimentos cresce e reduz pressões internas.',()=>{S.food+=10;S.stability+=2}],['🌊 Tempestade atlântica','Portos e comércio sofrem perdas temporárias.',()=>{S.trade-=3;S.infrastructure-=1}],['📚 Descoberta científica','Pesquisadores avançam uma técnica promissora.',()=>{S.science+=2;S.technology+=2}],['🧭 Navegadores estrangeiros','Uma potência estrangeira oferece uma oportunidade comercial.',()=>{S.trade+=4;S.diplomacyPower+=2}],['⚠️ Crise de abastecimento','A logística falha e parte dos estoques é consumida.',()=>{S.food-=7;S.stability-=3}],['🕊️ Aproximação diplomática','Uma potência reconsidera sua postura.',()=>{const ns=Object.values(S.nations);const n=ns[Math.floor(Math.random()*ns.length)];n.attitude=clamp(n.attitude+8,-100,100)}]];return pool[Math.floor(Math.random()*pool.length)]}
function ensureEconomyModel(){
 if(!S.economyModel)S.economyModel={prices:{food:1,wood:1,iron:1,machines:4,energy:2},lastFlow:{food:0,wood:0,iron:0,machines:0,energy:0,treasury:0},shortages:[],surplus:[]};
 if(!S.resourcePotential)S.resourcePotential={food:1.05,wood:1.05,iron:1,energy:1};
}
function simulateEconomyYear(){
 ensureEconomyModel();
 const p=PEOPLE_PROFILES[S.startPeopleId]||PEOPLE_PROFILES.custom; const pot=S.resourcePotential;
 const agro=Math.max(0,S.workforce.agro),fish=Math.max(0,S.workforce.pesca),mining=Math.max(0,S.workforce.minera),manu=Math.max(0,S.workforce.manufatura),mach=Math.max(0,S.workforce.industria),nav=Math.max(0,S.workforce.navegacao),services=Math.max(0,S.workforce.servicos);
 const foodProd=(agro*.42*pot.food*(p.food||1))+(fish*.55*pot.food), woodProd=(agro*.06*pot.wood*(p.wood||1))+(Math.max(0,S.workforce.construcao)*.035*pot.wood), ironProd=mining*.24*pot.iron*(1+S.infrastructure/180)*(1+S.industry/180), goods=manu*.16+mach*.48*(1+S.energy/180), machineProd=mach*.08*(1+S.industry/140), energyProd=Math.max(0,S.energy*.28)+mach*.035;
 const foodUse=Math.max(2,S.population/8500),woodUse=Math.max(1,S.industry*.055+S.infrastructure*.018),ironUse=Math.max(.5,S.industry*.025+mach*.05),energyUse=Math.max(1,S.industry*.075+S.urban*.012),machineWear=Math.max(.05,S.industry*.012);
 const flows={food:foodProd-foodUse,wood:woodProd-woodUse,iron:ironProd-ironUse,machines:machineProd-machineWear,energy:energyProd-energyUse};
 S.food=Math.max(0,S.food+flows.food);S.wood=Math.max(0,S.wood+flows.wood);S.iron=Math.max(0,S.iron+flows.iron);S.machines=Math.max(0,S.machines+flows.machines);S.energyStock=Math.max(0,S.energyStock+flows.energy);
 const scarcity=(stock,ideal)=>clamp((ideal-Math.max(0,stock))/Math.max(ideal,1)*100,0,80),idealFood=Math.max(25,S.population/450),idealWood=Math.max(20,S.industry*2),idealIron=Math.max(10,S.industry*1.2),idealEnergy=Math.max(15,S.industry*1.5);
 const pr=S.economyModel.prices;pr.food=clamp(1+scarcity(S.food,idealFood)/100*1.8,.65,3);pr.wood=clamp(1+scarcity(S.wood,idealWood)/100*1.5,.7,2.8);pr.iron=clamp(1+scarcity(S.iron,idealIron)/100*2,.7,3.5);pr.energy=clamp(2+scarcity(S.energyStock,idealEnergy)/100*2.5,1,5);pr.machines=clamp(4+scarcity(S.machines,Math.max(3,S.industry/8))/100*3,2,8);
 const marketOutput=goods*pr.wood*.35+S.trade*(.16+pr.food*.03)+nav*.3,taxBase=S.population/1800+S.urban*.8+services*.45,taxIncome=taxBase*(.55+S.economy/180),maintenance=S.industry*.22+S.infrastructure*.08+S.military*.08+S.energy*.06,net=taxIncome+marketOutput-maintenance;
 S.treasury=Math.max(0,S.treasury+net);S.economy=clamp(S.economy+goods*.025+marketOutput*.02-maintenance*.01);S.industry=clamp(S.industry+goods*.012-.01*maintenance);
 if(S.food<foodUse*.8){S.health=clamp(S.health-1.2);S.stability=clamp(S.stability-1.1);S.history.push({year:S.year,text:'Escassez alimentar pressionou preços e reduziu a estabilidade.'});} else if(S.food>idealFood*1.3){S.stability=clamp(S.stability+.2);}
 if(S.energyStock<energyUse*.65&&S.industry>15){S.industry=clamp(S.industry-.5);S.economy=clamp(S.economy-.4);}
 S.trade=clamp(S.trade+nav*.035+goods*.01);S.economyModel.lastFlow={...flows,treasury:net};S.economyModel.shortages=[];S.economyModel.surplus=[];
 if(S.food<idealFood*.65)S.economyModel.shortages.push('Alimentos');if(S.wood<idealWood*.6)S.economyModel.shortages.push('Madeira');if(S.iron<idealIron*.6)S.economyModel.shortages.push('Ferro');if(S.energyStock<idealEnergy*.6)S.economyModel.shortages.push('Energia');if(S.food>idealFood*1.5)S.economyModel.surplus.push('Alimentos');if(S.wood>idealWood*1.5)S.economyModel.surplus.push('Madeira');
}

function nextRound(free=false){if(!free&&S.actionsLeft===5)return toast('Escolha pelo menos uma ação ou use “Passar sem ações”.');const names=[...S.selectedActions];const ev=randomEvent();ev[2]();const growth=.007+S.health*.00005+S.education*.000025;S.researchPoints+=.35+S.science*.018+(S.institutions?.includes("academy")?.25:0);S.population*=1+growth;S.urban=clamp(S.urban+Math.max(.08,S.industry*.011+S.infrastructure*.003),0,96);S.economy=clamp(S.economy+S.industry*.015+S.education*.01-1);S.science=clamp(S.science+S.education*.018+S.technology*.006-.1);S.industry=clamp(S.industry+S.energy*.008-.06);S.technology=clamp(S.technology+S.science*.008);S.military=clamp(S.military-.04);S.readiness=clamp(S.readiness-1);S.infrastructure=clamp(S.infrastructure+S.industry*.004);S.health=clamp(S.health+S.education*.004-.02);S.stability=clamp(S.stability+(S.health>25?.1:-.2));simulateEconomyYear();
 S.workforce.industria=clamp(S.workforce.industria+.14,0,48);S.workforce.agro=clamp(S.workforce.agro-.12,8,60);S.workforce.ciencia=clamp(S.workforce.ciencia+(S.education>40?.05:.01),0,20);S.workforce.servicos=clamp(S.workforce.servicos+.04,0,25);const c=S.cities.saoLuis;c.pop*=1+growth*1.2;c.industry=clamp(c.industry+S.industry*.01);c.infra=clamp(c.infra+S.infrastructure*.008);c.science=clamp(c.science+S.science*.005);c.education=clamp(c.education+S.education*.004);c.health=clamp(c.health+S.health*.004);
 Object.values(S.nations).forEach(n=>{n.economy=clamp(n.economy+(Math.random()-.35)*1.5);n.science=clamp(n.science+(Math.random()-.2)*1.2);n.stability=clamp(n.stability+(Math.random()-.5));n.military=clamp(n.military+(Math.random()-.35));if(n.tension>70)n.attitude-=1;}); Object.entries(S.warStatus).forEach(([id,status])=>{if(status!=='war')return;const n=S.nations[id];if(!n)return;n.tension=clamp(n.tension+2);if(Math.random()<.16){S.economy=clamp(S.economy-1.5);S.readiness=clamp(S.readiness-2);S.history.push({year:S.year,text:`Conflito prolongado com ${n.name}: desgaste logístico e econômico.`})}});Object.entries(S.relations).forEach(([id,r])=>{if(S.alliances.includes(id)){r.trust=clamp(r.trust+1);S.nations[id].tension=clamp(S.nations[id].tension-1)}}); Object.entries(S.tradeRoutes||{}).forEach(([id,route])=>{const n=S.nations[id],r=S.relations[id];if(!n||!r)return;if(S.warStatus[id]==='war'){delete S.tradeRoutes[id];S.trade=Math.max(0,S.trade-6);S.economy=Math.max(0,S.economy-2);S.history.push({year:S.year,text:`Rota comercial com ${n.name} interrompida pela guerra.`});return;}route.level=clamp(Number(route.level)||1,1,5);route.capacity=Number(route.capacity)||Math.round(10+route.level*4);route.risk=clamp(Number(route.risk)||12);route.profit=Number(route.profit)||Math.round(4+route.level*2);if(Math.random()*100<route.risk*.035){S.treasury=Math.max(0,S.treasury-2);S.trade=Math.max(0,S.trade-1);S.history.push({year:S.year,text:`Risco marítimo afetou a rota com ${n.name}; perdas logísticas temporárias.`});}else{S.treasury+=route.profit;S.trade+=.8+route.level*.12;S.economy+=.25;S.influence[id]=(S.influence[id]||0)+.35;route.level=clamp(route.level+.025,1,5);route.capacity=Math.round(10+route.level*4);route.profit=Math.round(4+route.level*2);}});
 S.year++;S.round++;S.actionsLeft=5;S.selectedActions=[];S.history.push({year:S.year,text:`${ev[0]} — ${ev[1]}`});for(const m of milestones)if(m[0]===S.year)S.history.push({year:S.year,text:`${m[1]} — ${m[2]}`});S.lastGlobal=globalSnapshot();S.lastReport={actions:names.length?names:["Passagem livre — nenhuma ação direta"],free,event:ev[0],eventText:ev[1],population:S.population,economy:S.economy,science:S.science,industry:S.industry,military:S.military,technology:S.technology};clampAll();render();showReport()}
function globalSnapshot(){return{year:S.year,powers:Object.entries(S.nations).map(([id,n])=>({id,name:n.name,flag:n.flag,military:Math.round(n.military),economy:Math.round(n.economy),science:Math.round(n.science),stability:Math.round(n.stability),attitude:Math.round(n.attitude),tension:Math.round(n.tension),territory:Math.round(n.territory),alliance:n.alliance}))}}
function showReport(){const r=S.lastReport,g=S.lastGlobal||globalSnapshot();$("roundReport").innerHTML=`<h2>🌴 UPAON-AÇU — ROUND ${S.round}</h2><p class="muted">ANO ${S.year} • ${era()}</p><div class="card"><h3>Decisões executadas</h3><p>${r.actions.map(x=>'• '+x).join('<br>')}</p></div><div class="card"><h3>🎲 ${r.event}</h3><p class="muted">${r.eventText}</p></div><div class="report-grid">${Object.entries({População:fmt(r.population),Economia:Math.round(r.economy)+"/100",Ciência:Math.round(r.science)+"/100",Indústria:Math.round(r.industry)+"/100",Tecnologia:Math.round(r.technology)+"/100",Militar:Math.round(r.military)+"/100"}).map(([k,v])=>`<div class="report-box"><small>${k}</small><b>${v}</b></div>`).join('')}</div><div class="card"><h3>🌎 Equilíbrio de poder</h3>${g.powers.sort((a,b)=>b.military-a.military).map(n=>`<div class="row"><span>${n.flag} ${n.name} ${n.alliance?'🤝':''}</span><b>Mil ${n.military} • Econ ${n.economy} • Ciência ${n.science} • Tensão ${n.tension}</b></div>`).join('')}</div><p class="muted">Você recebeu 5 novos pontos de ação. O próximo ano só avança quando você decidir.</p>`;$("reportModal").classList.remove('hidden')}
function diplomaticScore(id){const n=S.nations[id],d=S.relations[id]||{};return Math.round(clamp((n.attitude||0)*.45+(d.trust||0)*.35+(d.trade||0)*.2-(n.tension||0)*.25,-100,100))}
function renderDiplomacy(){$("diplomacyGrid").innerHTML=Object.entries(S.nations).map(([id,n])=>{const d=S.relations[id]||{trust:0,trade:0},war=S.warStatus[id]==='war',ally=S.alliances.includes(id),route=!!S.tradeRoutes?.[id],score=diplomaticScore(id),r=S.tradeRoutes?.[id];return `<div class="dip ${war?'at-war':''}"><h3>${n.flag} ${n.name}</h3><div class="relation">${war?'⚔️ EM GUERRA':ally?'🤝 ALIADO':route?'🚢 ROTA ATIVA':score>=35?'🟢 aproximação':score<=-20?'🔴 deterioração':'🟡 competição'}</div><div class="row"><span>Índice diplomático</span><b>${score}</b></div><div class="row"><span>Atitude</span><b>${Math.round(n.attitude)}</b></div><div class="row"><span>Confiança</span><b>${Math.round(d.trust)}</b></div><div class="row"><span>Comércio</span><b>${Math.round(d.trade)}</b></div><div class="row"><span>Influência</span><b>${Math.round(S.influence[id]||0)}</b></div><div class="row"><span>Força</span><b>${Math.round(n.military)}</b></div><div class="row"><span>Rota</span><b>${route?`nível ${r.level.toFixed(1)} • ${r.product}`:'—'}</b></div>${route?`<div class="route-mini">Capacidade ${r.capacity} • lucro +¤${r.profit}/ano • risco ${Math.round(r.risk)}%</div>`:''}</div>`}).join('')}
function renderTimeline(){$("timeline").innerHTML=S.history.slice().reverse().slice(0,80).map(e=>`<div class="event"><div class="date">${e.year}</div><div class="txt">${e.text}</div></div>`).join('')}
function drawChart(){const c=$("chart");if(!c)return;const ctx=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth||800,h=260;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const hist=S.censuses.length?S.censuses.map(x=>x.population):[S.population];if(hist.length<2)hist.unshift(S.population*.92);const min=Math.min(...hist),max=Math.max(...hist);ctx.strokeStyle='#214737';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=35+i*60;ctx.beginPath();ctx.moveTo(20,y);ctx.lineTo(w-20,y);ctx.stroke()}ctx.strokeStyle='#67e09e';ctx.lineWidth=3;ctx.beginPath();hist.forEach((v,i)=>{const x=20+i*(w-40)/(hist.length-1),y=225-(v-min)/Math.max(1,max-min)*180;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#91b1a2';ctx.font='11px system-ui';ctx.fillText('População — censos registrados',20,18);ctx.fillText(fmt(min),20,248);ctx.fillText(fmt(max),20,32)}
function clampAll(){ensureEconomyModel();['stability','economy','science','industry','technology','military','diplomacyPower','education','health','energy','infrastructure','readiness','urban','trade'].forEach(k=>S[k]=clamp(S[k]));S.population=Math.max(100,S.population);S.treasury=Math.max(0,S.treasury);['food','iron','wood','machines','energyStock'].forEach(k=>S[k]=Math.max(0,S[k]));Object.values(S.nations).forEach(n=>{n.tension=clamp(n.tension);n.military=clamp(n.military);n.economy=clamp(n.economy);n.science=clamp(n.science);n.stability=clamp(n.stability);n.attitude=clamp(n.attitude,-100,100)});Object.values(S.relations||{}).forEach(r=>{r.trust=clamp(r.trust);r.trade=clamp(r.trade);r.science=clamp(r.science)});if(!S.tradeRoutes||typeof S.tradeRoutes!=="object")S.tradeRoutes={};if(!S.economyModel)S.economyModel=structuredClone(initial.economyModel);if(!S.resourcePotential)S.resourcePotential=structuredClone(initial.resourcePotential);Object.keys(S.tradeRoutes).forEach(id=>{if(!S.nations[id])delete S.tradeRoutes[id]})}
function save(){localStorage.setItem(KEY,JSON.stringify(S));$("saveState").textContent='● salvo agora';toast('Campanha V10 salva neste navegador.')}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY)||localStorage.getItem('upaon-acu-v8.1')||'null');if(!x)return toast('Nenhum save V10/V9 encontrado.');S=Object.assign(structuredClone(initial),x);S.nations=Object.assign(structuredClone(nationTemplate),x.nations||{});const oldRelations=(x.relations&&typeof x.relations==='object')?x.relations:((x.diplomacy&&typeof x.diplomacy==='object')?x.diplomacy:{});S.relations=Object.assign(structuredClone(initial.relations),oldRelations);S.diplomacyPower=Number.isFinite(+x.diplomacyPower)?+x.diplomacyPower:(typeof x.diplomacy==='number'?+x.diplomacy:18);S.selectedRegion=x.selectedRegion||'upaon';S.mapMode=x.mapMode||'world';S.actionsLeft=Number.isFinite(+S.actionsLeft)?clamp(+S.actionsLeft,0,5):5;S.selectedActions=Array.isArray(S.selectedActions)?S.selectedActions:[];S.alliances=Array.isArray(S.alliances)?S.alliances:[];S.influence=x.influence||{};S.warStatus=x.warStatus||{};S.tradeRoutes=(x.tradeRoutes&&typeof x.tradeRoutes==='object')?x.tradeRoutes:{};S.researchPoints=Number.isFinite(+x.researchPoints)?+x.researchPoints:0;S.projects=Object.assign({ships:0,generators:0,aircraft:0,computers:0},x.projects||{});S.institutions=Array.isArray(x.institutions)?x.institutions:[];S.territories=Object.assign(structuredClone(initial.territories),x.territories||{});S.researchPoints=Number.isFinite(+S.researchPoints)?+S.researchPoints:3;Object.entries(S.tradeRoutes||{}).forEach(([id,r])=>{r.level=Number(r.level)||1;r.capacity=Number(r.capacity)||14;r.profit=Number(r.profit)||6;r.risk=Number(r.risk)||12;r.product=r.product||'comércio geral';});S.startPeopleId=x.startPeopleId||"custom";S.censuses=Array.isArray(S.censuses)?S.censuses:[];S.history=Array.isArray(S.history)?S.history:[];$("startScreen").classList.add('hidden');clampAll();render();toast('Campanha V10 carregada.') }catch(e){console.error(e);toast('Save inválido.')}}
function newGame(){if(confirm('Começar uma nova campanha V9?')){$("startScreen").classList.remove('hidden');S=structuredClone(initial);S.actionsLeft=5;S.diplomacyPower=18;S.mapZoom=1;setupPreview();render();}}
function toast(t){const x=$("toast");x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2300)}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel-page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='populacao')drawChart()});
$("nextRound").onclick=()=>nextRound(false);$("freeRound").onclick=()=>nextRound(true);$("attackBtn").onclick=strategicAttack;$("spyBtn").onclick=espionage;$("censusBtn").onclick=()=>doCensus(false);$("tradeTreaty").onclick=()=>treaty('trade');$("scienceTreaty").onclick=()=>treaty('science');$("nonAggression").onclick=()=>treaty('peace');$("saveBtn").onclick=save;$("loadBtn").onclick=load;$("newBtn").onclick=newGame;$("reportBtn").onclick=()=>{if(S.lastReport)showReport();else toast('Ainda não há relatório.')};$("closeModal").onclick=()=>$("reportModal").classList.add('hidden');$("reportModal").onclick=e=>{if(e.target.id==='reportModal')e.currentTarget.classList.add('hidden')};
if($("allianceBtn"))$("allianceBtn").onclick=alliance;if($("tradeRouteBtn"))$("tradeRouteBtn").onclick=tradeRoute;
document.querySelectorAll('.map-node.world').forEach(b=>b.onclick=()=>{S.selectedRegion=b.dataset.region;renderMap()});document.querySelectorAll('.map-mode').forEach(b=>b.onclick=()=>{S.mapMode=b.dataset.mapMode;renderMap()});if($("mapZoomIn"))$("mapZoomIn").onclick=()=>{S.mapZoom=clamp((S.mapZoom||1)+.15,.85,1.6);renderMap()};if($("mapZoomOut"))$("mapZoomOut").onclick=()=>{S.mapZoom=clamp((S.mapZoom||1)-.15,.85,1.6);renderMap()};if($("mapReset"))$("mapReset").onclick=()=>{S.mapZoom=1;renderMap()};
window.addEventListener('resize',drawChart);
render();
})();
